---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: renovate-secrets
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_HOST_RULES: AgAvGgpVwFC5eCiK0so5Br2VlJH0nWVN6NKLH70X/L6kE7rystrO42kbIIMwsuFT/PiZf9nwuywJIwjei6d2qK+tUWXeVUfMt/4HDr5c8hISC5om7VV64jRvCo80mcbahJJX8FdB3TcCFQ6sc9PqVWNoNa/aHwa/eTW6lmaUMJEjDV4X9FwsL1Vq5Gt2IK1AoU0+SMPucavCJJS9KEishBhUYBF0zwNQHGaJlQfxcxsmblisGtreUIHjQDjYraIu/17RVEzMLzEKSi8wWeo7Ztgd9DqUntH1mGfTuPomBpKydzQdeR0gsCx50TXejuBLS6DAwdX0meZ30/q/I53AeQ2RYA7zwiKs6+NGBpqT8zuOTcdyhduj+nOMekNo6+W4x6C59DDyxnCwy9IAPOaxfiyFLy3UqGvP0EsJ9uL0NN4ZgNj+y3JokPygQw1IMSx/p1PgGCnTQWBs/d+oB/cGmY8NKCwivd6klFaDhCf168ijdH94t9ie3U8y8mRBG9CwCl0tUPyAsMnemJdLyguXnRzQGe2fBRSG/TJCaQf37HkWz2ssV05kcwZUks1CLxJ6wfPQ8ub9rKhPTRFRKNx9rLOXw3/IXjjrqUp/UVgZSCnwr2/taJdPnImpjtnEMIMv1s8kbrJccT09sJ72pEmC3fWY9I/JlJ/JFjXItLyoptDRv5KIQjLlnJ4+vtaXUNiqvlgwugdqAFWUtbS/AlaYZ2jJsz0rEWR5EdChIGXELk0IhAUPMMwhMFoslyFQ1S41Gy3xDbxSuzwSZTRqq1uSgqloIr/JdMF/H/MbKn+YKBkM4raSoPA/vfbTTNcO/FEu+w+l96r7wybUawBjtpgWL9mvzp3i6T6hMs5iIMsj650MdtuP0sMm+vFpcnRmMogHJSRcwlo5LiYJKvFuMi/6MORqWGwKgcPOVS2v01rNpf8ebvEhoswRubcviCiTA0l6UNXWov/R82jJofIPEztsTZz9rvo6kHI=
    token: AgC/1Hg5lJDiTWBi5C88Aif+B0jpW4spLOrpIcyhB9cFdJ6Mx1WF08eUxatb9pSQqX8Dzg4Sm5SsCHZNmlwjC74sGohWWyjrN30CixzDiE2HHZCa+SDwyRqXBAove6rK5QIsWH0KFeMd4AK5I0NAKp6Xtw2WTMskkSQaxCv5JybFNjtzSzgpsn+N6x3/veZ066zlba3qxDqKKpX7Jao5MIAths1ZOsnErPQGpSN2AbyUCmJP2wW41KuD485w9wUDAip+n1arHMzgYDsHORXa+t9L5Z0fVPLYM0TV6yUuoRldQPlKkqQuPwdc3nnwn2n08ea7Fkk400O9Usg2eu75hilQMECYGQDKFdiFAxKQFECstSfIqgGQIG1TVZgvMyjkrzzYxUFyfExKvoxZ2s14lv9OzvIMP4TzH62O6jWyRA2wULtmjltpo+pnxywyO4P+HxiJLsumma4iiNYdmhcXp3+SQW020uDg6lr+ZEiC5uyBJIAjIPjwFMgtWI+WcobXnJc/VFfrJuXURcTTvapHh2bzdTMv1c4wgJatfBsJgKe5lAkPaQsqsk1XGj0R38LcD8mnjuTQ009DPUK46l1gIM80ZK8pAgGZ6n3ectx9uCcAC+MPYBDjFC8Te8Z3xAaywJttIx+IqZjJoRymyOcMeNZLCa3hVSbkc+ivQFJYQcP/SJk4c+w9fhIq4R/bytt8h6qJHbZhfKtB4H9ynfY7/nT/+D73EeQ8nUSOWuISF2PRbgRMZihYJr3osrlL2iRoJJyqbmQi6zEcYAagYnqhMY0sTGzEkwaJ1NVNWYPSVBG6fKvciLOQAtmwfabcZcM=
  template:
    metadata:
      creationTimestamp: null
      name: renovate-secrets
      namespace: renovate
    type: Opaque
