---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: renovate-secrets
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_HOST_RULES: AgAnyN5m4NSxOC1ZjjQVrLQ13daUytguHGJILRfGoQ64hV58+OlW7Hz0tluikjpvTtKazoFDbJk8JtgoTeFpaDh7fSh/DAuf0ctdJqlxD2O5kUF4OcyzriX6gQ2KQzT8wADu5u3Z/rMmMtthClykwUzhKC/4/UiwASxCWIllhIr5phLCUuuIpJ3uY9QPMSIbISuJpKhy8VEBQipmLth9/wo+Bf2+bH/eZM4vieZUtyZG71mEWFHmUnLjFQjgYVokQ1yU6OCrpCT9fiJYY2VwG7/Vtf95/GMcrhdWUn3f26149t7FmOnXhNrN/iabq6EoXneCwHOMMHpAUUpL2vz46KhvauNpeMo7aK7mSKajA0uAVod4WqnK+1kAfxjhUBEov5HzpaxvIrw3j929AQ0yr/WNXgQytLTIGCNYAA+lr1/wtQLJbaljggVcZQmv8y40YWVIQ/t+bNvhVoSvKBAbaB2vJjYUOqn437VDEQcLEGwurQ2Ecyb8z3m7hdpE05ravX14ib7kG7xCvn7u8+Tn/iEeCGfNVv55uhZKw1dpraJ0XW+g+fIGl389ieNbbJDQzwBn9VRDZQL6mZFBRi8FbwQui6DfMvazb0FJdTW8k+ENYgADB+XiYRJO7CLzc8f4thqqxyViku+1WVtmc5N/bB+2FO/bAEFkES5Q8g9da6K5aC0r5pK4KqfYteWgzoejo1sa1Wy9I/BKVxNAIfMIuyzgHTvyOu5f/TOxESNwwLdK1cY1y0Ip9b8B6aigijVe+hKxLsP+GGJdMS5oFhDvgXGW36coel4HWxTpw5BQ4PvSDANTuycVvugtI3QeJFMcLLcjV9vGf12TMAIft9jcWrCESG2e/QGoMMl6AWA=
    token: AgAdtv6O0johpeib9M54YPY4bNnVoSDrtCemQ6QFx4RC5Xmg3NbZ00jx3hkW/DUt/H4SzVvW/UQOZkn1SStGcO+Fab2Z5fNgayVI57DcgsvUtj/HmDA3KkNGMAl0z/Kw2Wu6CvXw2gCoOyQ59s4w5+JqxQVpusPLsdXcempPDpQWIVgBG7VQhW7gkO86UnVGPZ2fgczclanWqMm3JzIuW3cm4kQWkOdVEG556/MBPVx8V+pcI7/OHvoEof8poCwq5bZ1PYdiG33B958vMaesQB+9g1NZ/cCc1zysFFgAWdKQq/NWb5tgdWoC86rXF+YKA71E8jgANrPjd/Y0kL+DJZgpMA40PKKZ+fyIxf4uwKeE38/q1un+W2wjMZOJrPlyY8/0pnN6c8pRcJjZvkDmVpy/rMne34jlYJhnk0Q1YyZY15HX0WFs9wAeWhOSLsuyS/QCh61S+h2ncIFXXhrCyrkLWfH/XH7+QgXPXNTA9feKjPhScf9BjVjVnrwSSp47lXwhiUKr9qdeBp7tC1h53bh2GPFXP9ODVGWNfaMoCtijHV4Vw5f+TekeHUInOpCbC198F/TgYgNp7Arl2AI1TwkCPFSapyulFPC/p5D1H6R35DqOnvKu5RwJdBgSry0k8SYSPLg9NADUKkMy2jD5R3HcwqgbqUVNxD5lxiAHurNvfGFLgmszpww3CmCwk2k+D9rmdLxYR6Oa2XMoO5IdCZ8YcBpIrMhbWiRnFj8hFCVjRGB4vwJUR8NCE/fTQFSN2MagGK3zPn33BK+KRVN+T/fk0rTfvLSWM6465k0xZAVs7evgcn7QAxzFpylLz0s=
  template:
    metadata:
      creationTimestamp: null
      name: renovate-secrets
      namespace: renovate
    type: Opaque
