apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sparkyfitness-db-pvc
  namespace: sparky-fitness
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client