apiVersion: apps/v1
kind: Deployment
metadata:
  name: mas-postgres
  namespace: synapse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mas-postgres
  template:
    metadata:
      labels:
        app: mas-postgres
    spec:
      nodeSelector:
        affected_vlan: "50"
      containers:
        - name: postgres
          image: docker.io/library/postgres:18@sha256:a02db8cac496f15b094798a38254f14d6e00741f709360e5e00bb6668ea31636
          envFrom:
            - configMapRef:
                name: mas-db-cm 
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mas-secrets
                  key: MAS_POSTGRES_PASSWORD
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql
              subPath: pgdata
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: mas-db-pvc