apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: base-gateway
  namespace: cluster-gateway  # Dedicated namespace for the gateway
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  gatewayClassName: nginx
  listeners:
  - name: http
    hostname: "actual-budget.hoareau-marion.eu"
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Same
  - name: https
    hostname: "actual-budget.hoareau-marion.eu"
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
        - name: actual-budget-hoareau-marion-eu-tls
    allowedRoutes:
      namespaces:
        from: Same
