apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: base-gateway
  namespace: cluster-gateway  # Dedicated namespace for the gateway
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  gatewayClassName: nginx
  listeners:
  ###
  # ACTUAL BUDGET
  ###
  - name: http
    hostname: "actual-budget.hoareau-marion.eu"
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            gateway-access: actual-budget
  - name: https
    hostname: "actual-budget.hoareau-marion.eu"
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
        - name: actual-budget-hoareau-marion-eu-tls
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            gateway-access: actual-budget
  ###
  # CODE SERVER
  ###
  - name: code-server-http
    hostname: "code-server.hoareau-marion.eu"
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            gateway-access: code-server

  - name: code-server-https
    hostname: "code-server.hoareau-marion.eu"
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
        - name: code-server-hoareau-marion-eu-tls   # Secret must exist in gateway’s namespace
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            gateway-access: code-server
