apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-egress-config
  namespace: cluster-gateway
data:
  envoy.yaml: |
    admin:
      access_log_path: /dev/null
      address:
        socket_address: { address: 127.0.0.1, port_value: 9901 }
    
    static_resources:
      listeners:
      # TCP egress listener (80/443 → 8080)
      - name: tcp_egress_listener
        address:
          socket_address: { address: 0.0.0.0, port_value: 8080 }
        filter_chains:
        - filters:
          - name: envoy.filters.network.tcp_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
              stat_prefix: egress_tcp
              cluster: external_tcp
              tproxy_bind: true
      
      # UDP egress listener (DNS → 5300)
      - name: udp_egress_listener
        address:
          socket_address: { address: 0.0.0.0, port_value: 5300, protocol: UDP }
        udp_listener_config:
          downstream_socket_config:
            max_rx_datagram_size: 9000
        listener_filters:
        - name: envoy.filters.udp_listener.udp_proxy
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.UdpProxyConfig
            stat_prefix: egress_udp
            matcher:
              on_no_match:
                action:
                  name: route
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.Route
                    cluster: external_udp
            upstream_socket_config:
              max_rx_datagram_size: 9000
      
      # ORIGINAL_DST clusters - SIMPLIFIED (no custom LB policy needed)
      clusters:
      - name: external_tcp
        connect_timeout: 30s
        type: ORIGINAL_DST
        lb_policy: CLUSTER_PROVIDED
        load_assignment:
          endpoints:
          - lb_endpoints: []
      
      - name: external_udp
        connect_timeout: 30s
        type: ORIGINAL_DST
        lb_policy: CLUSTER_PROVIDED
        load_assignment:
          endpoints:
          - lb_endpoints: []
