apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: envoy-egress
  namespace: cluster-gateway
spec:
  selector:
    matchLabels:
      app: envoy-egress
  template:
    metadata:
      labels:
        app: envoy-egress
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          egress-nad-home-desk-r04-mer01-10-mkub-01@home-desk-r04-mer01-10-mkub-01,
          egress-nad-home-desk-r04-mer01-10-wkub-01@home-desk-r04-mer01-10-wkub-01,
          egress-nad-home-desk-r04-mer01-10-wkub-02@home-desk-r04-mer01-10-wkub-02
    spec:
      hostNetwork: true      
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - home-desk-r04-mer01-10-mkub-01
                - home-desk-r04-mer01-10-wkub-01
                - home-desk-r04-mer01-10-wkub-02
      containers:
      - name: envoy
        image: envoyproxy/envoy:v1.29.3
        args:
        - -c
        - /etc/envoy/envoy.yaml
        volumeMounts:
        - name: config
          mountPath: /etc/envoy
        # ports:
        # - containerPort: 80
        #   name: http
        # - containerPort: 443
        #   name: https
        securityContext:
          capabilities: { add: ["NET_ADMIN", "NET_RAW"] } 
        initContainers:
        - name: iptables-redirect
          image: busybox:1.36
          command: ["/bin/sh"]
          args:
          - -c
          - |
            iptables -t nat -N KUBE-EGRESS-PROXY 2>/dev/null || true
            iptables -t nat -F KUBE-EGRESS-PROXY 2>/dev/null || true
            iptables -t nat -X KUBE-EGRESS-PROXY 2>/dev/null || true
            
            # Skip ONLY cluster-internal traffic
            iptables -t nat -A KUBE-EGRESS-PROXY -m owner --uid-owner root -j RETURN
            iptables -t nat -A KUBE-EGRESS-PROXY -d 10.43.0.0/16 -j RETURN     # Service CIDR
            iptables -t nat -A KUBE-EGRESS-PROXY -d 10.42.0.0/16 -j RETURN     # Pod CIDR
            iptables -t nat -A KUBE-EGRESS-PROXY -s 10.42.0.0/16 -j RETURN     # From pods
            
            # Proxy ALL VLAN50 traffic → Envoy → external
            # NO VLAN50 RETURN rule - let it hit proxy
            
            # Redirect external-bound traffic
            iptables -t nat -A KUBE-EGRESS-PROXY -p tcp --dport 80 -j REDIRECT --to-ports 8080
            iptables -t nat -A KUBE-EGRESS-PROXY -p tcp --dport 443 -j REDIRECT --to-ports 8080
            iptables -t nat -A KUBE-EGRESS-PROXY -p udp --dport 53 -j REDIRECT --to-ports 5300
            
            iptables -t nat -A OUTPUT -j KUBE-EGRESS-PROXY
            echo "iptables setup complete - VLAN50 proxied"

          securityContext:
            capabilities:
              add: ["NET_ADMIN"]

      volumes:
      - name: config
        configMap:
          name: envoy-egress-config

