apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  labels:
    hoareau-marion.eu/category: infrastructure
spec:
  project: homelab
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    chart: external-dns
    targetRevision: 1.14.3
    helm:
      values: |
        fullnameOverride: external-dns
        logLevel: info
        
        # Configure External-DNS to use the webhook provider
        provider:
          name: webhook
           # OPNsense Webhook Sidecar Container
          webhook:
            image:
              repository: ghcr.io/crutonjohn/external-dns-opnsense-webhook
              tag: main
            env:
              - name: OPNSENSE_HOST
                value: "https://opnsense.home.hoareau-marion.eu" # Replace with your OPNsense internal IP/URL
              - name: OPNSENSE_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: external-dns-opnsense-secret
                    key: api_key
              - name: OPNSENSE_API_SECRET
                valueFrom:
                  secretKeyRef:
                    name: external-dns-opnsense-secret
                    key: api_secret
            livenessProbe:
              httpGet:
                path: /healthz
                port: 8080
            readinessProbe:
              httpGet:
                path: /healthz
                port: 8080
        # Sources to monitor for domain generation
        sources:
          - gateway-httproute
          
        # Restrict automated management to your target domain
        domainFilters:
          - hoareau-marion.eu
          
        registry: "noop"
        
       
  destination:
    server: https://kubernetes.default.svc
    namespace: cluster-gateway
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true