apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      nodeSelector:
        affected_vlan: "50"
      initContainers:
      - name: setup-run
        image: busybox@sha256:fd8d9aa63ba2f0982b5304e1ee8d3b90a210bc1ffb5314d980eb6962f1a9715d
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        command:
          - sh
          - -c
          - |
            chmod 0755 /run
            chown 3102:3100 /run
        volumeMounts:
        - name: run-tmpfs
          mountPath: /run
      containers:
      - name: sonarr
        image: lscr.io/linuxserver/sonarr:4.0.19@sha256:633e0e66d85ce4e9172608a37d3d24e124b3e485fc0d946f533c3bb5875227e9
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 3102
          runAsGroup: 3100
        envFrom:
        - configMapRef:
            name: config-map
        ports:
        - name: sonarr
          containerPort: 8989
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /config
        - name: media-data
          mountPath: /media_data
        - name: run-tmpfs
          mountPath: /run
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1500m"
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: config-pvc
      - name: media-data
        persistentVolumeClaim:
          claimName: media-data-pvc
      - name: run-tmpfs
        emptyDir:
          medium: Memory