apiVersion: v1
kind: ConfigMap
metadata:
  name: gluetun-cm
  namespace: qbittorrent
data:
  VPN_SERVICE_PROVIDER: "protonvpn"
  VPN_TYPE: "wireguard"
  WIREGUARD_IMPLEMENTATION: "userspace"
  SERVER_COUNTRIES: "France"
  WIREGUARD_MTU: "1320"
  
  VPN_PORT_FORWARDING: "on"
  VPN_PORT_FORWARDING_STATUS_FILE: "/gluetun/forwarded_port"
  PORT_FORWARD_ONLY: "on"

  DOT: "off"
  TZ: "Europe/Paris"

  HEALTH_TARGET_ADDRESS: "1.1.1.1:53"
  HEALTH_VPN_DURATION_INITIAL: "30s"

  BORINGPOLL_GLUETUNCOM: "on"
  
  FIREWALL_OUTBOUND_SUBNETS: "10.42.0.0/16,10.43.0.0/16,10.10.20.0/24,10.10.50.0/24,10.0.0.0/24"
  FIREWALL_INPUT_PORTS: "8080"