apiVersion: v1
kind: ConfigMap
metadata:
  name: gluetun-cm
  namespace: qbittorrent
data:
  VPN_SERVICE_PROVIDER: "protonvpn"
  VPN_PORT_FORWARDING: "on"
  VPN_PORT_FORWARDING_STATUS_FILE: "/gluetun/forwarded_port"
  SERVER_COUNTRIES: "France"
  PORT_FORWARD_ONLY: "on"
  WIREGUARD_MTU: "1292"
  TZ: "Europe/Paris"
  VPN_TYPE: "wireguard"
  DOT: "off"
  DNS_ADDRESS: "10.10.50.1"
  DNS_KEEP_NAMESERVER: "on"
  FIREWALL_OUTBOUND_SUBNETS: "10.10.50.1/32,10.42.0.0/16,10.43.0.0/16,10.0.0.0/24"