---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gluetun-secrets
  namespace: qbittorrent
spec:
  encryptedData:
    WIREGUARD_PRIVATE_KEY: AgDKMRUXWJWAaj7//siIEEryXVqX8ojIpGi5m6HTwF3PJvyWYzT2f98KSD4AfaTOA8s3S6E37bnScX3C7neQsgr2URHT0MJft3bEzE2asItdiCsPDWIx27CAh+StUe4CNQCnsnPkd1+Ht6G7PUQJHKaoQhloe6pwE089QmTakqOYt/YUSqGAyIuFbFbyZ7iorBqaTHTMIK6xcifSkIhpSdj0ufXu5rgU4J63FIph0NJNeIK57P7KiLvC6Ay4ZVYiMepgS+H6hWFfOzPXA6nDA3QMXkKOccjHkZEmFTVO4IKOc+e+Hhlvhv+q7fw42jwm4z58o/fRG2UbJODmwofFxTAUA+wl1uja2e1Y8l2GFpOoeML8w492OX4XpjBJs4dizksUk/5d4mxlj0d6BMKuQfYcL2qKRjZy03VjeVAbTXVlJuzranH5ftH/geSg+b2nrz3RR8ILmUKY1pX03XkL5PnAmV5i3lQYP1vsgvtJaFMdm0l/VTGug9vLFUyifDeohNn5WkLBXhmDFvGz10PV8NLt4DP+2RE1CtnNhKU4KOabzoZnALpo29lNPOgR7zlWw5UrwfAXE6jjILoaWK4zUD+I/X3IFzsIx9bEXOnD+G33JZ5EZ4GgV+IOi5esXg+goZu2E927KCmj9+PF14pnIWB7LanAyQsr7FCY1jqsjg31Bu/gtrhlpXiiybfeHuGUiJIO9OYSL2JxARJYaJ2CvZr0z9IIwQpH+g1Cvy0gwhoobkfnuGjW30Omgghe6Q==
  template:
    metadata:
      name: gluetun-secrets
      namespace: qbittorrent
    type: Opaque
