apiVersion: v1
kind: Service
metadata:
  name: pve-exporter-svc
  namespace: prometheus-exporters
spec:
  selector:
    app: pve-exporter
  ports:
    - port: 9221
      targetPort: 9221
      name: http