apiVersion: v1
kind: ConfigMap
metadata:
  name: server-cm
  namespace: sparky-fitness
data:
  SPARKY_FITNESS_OIDC_AUTH_ENABLED: "true"
  SPARKY_FITNESS_DISABLE_EMAIL_LOGIN: "false"
  SPARKY_FITNESS_DB_PORT: "5432"
  SPARKY_FITNESS_LOG_LEVEL: "info"
  ALLOW_PRIVATE_NETWORK_CORS: "true"
  SPARKY_FITNESS_EXTRA_TRUSTED_ORIGINS: ""
  SPARKY_FITNESS_DB_USER: "sparky"
  SPARKY_FITNESS_DB_HOST: "db"
  SPARKY_FITNESS_DB_NAME: "sparkyfitness_db"
  SPARKY_FITNESS_FRONTEND_URL: "https://sparky-fitness.hoareau-marion.eu"
  SPARKY_FITNESS_DISABLE_SIGNUP: "false"
  SPARKY_FITNESS_EMAIL_HOST: "smtp.home.hoareau-marion.eu"
  SPARKY_FITNESS_EMAIL_PORT: "25"
  SPARKY_FITNESS_EMAIL_SECURE: "false"
  SPARKY_FITNESS_EMAIL_FROM: "SparkyFitness <homelab@hoareau-marion.eu>"
  SPARKY_FITNESS_SERVER_HOST: "sparkyfitness-server"
  SPARKY_FITNESS_SERVER_PORT: "3010"
  TZ: 'Europe/Paris'