apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: synapse
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-client
