apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: sroom-prt01-60-announcement
  namespace: kube-system
spec:
  interfaces: ["ens18.60"]
  loadBalancerIPs: true
  serviceSelector:
    matchLabels:
      is-sroom-prt01: "true"
  nodeSelector:
    matchLabels:
      affected_vlan: "60"