apiVersion: v1
kind: ConfigMap
metadata:
  name: cm
  namespace: sftpgo
data:
  DISABLED_LOGIN_METHODS: "9"
  SFTPGO_FTPD__BINDINGS__0__PORT: "2121"         
  SFTPGO_FTPD__BINDINGS__0__TLS_MODE: "0"       
  SFTPGO_FTPD__PASSIVE_PORT_RANGE__START: "50000" 
  SFTPGO_FTPD__PASSIVE_PORT_RANGE__END: "50030"
  