apiVersion: v1
kind: Service
metadata:
  name: sftpgo
  namespace: sftpgo
  labels:
    app: sftpgo
  annotations:
    io.cilium/lb-ipam-ips: "sftpgo-pool"
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: sftp
    port: 2022
    targetPort: 2022
  - name: ftp-control
    protocol: TCP
    port: 2121            
    targetPort: 2121
  - name: ftp-passive
    protocol: TCP
    port: 50000
    targetPort: 50000
    endPort: 50030
  selector:
    app: sftpgo
