apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: sftpgo-pool
spec:
  blocks:
  - start: "10.10.50.176" 
    stop: "10.10.50.180"
  serviceSelector:
    matchExpressions:
    - key: app
      operator: In
      values: ["sftpgo"]
