# apps/sftpgo/shared-sftpgo-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-sftpgo-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  nfs:
    server: truenas.local.hoareau-marion.eu
    path: /mnt/homelab-pool/homelab/k3s_apps/shared-consume  
