apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-proxy-prowlarr-cm
  namespace: shared-authentication
data:
  oauth2-proxy.cfg: |
    provider = "keycloak-oidc"
    oidc_issuer_url = "https://keycloak.hoareau-marion.eu/realms/milkyway"
    client_id = "prowlarr_v2"
    http_address = "0.0.0.0:4180"
    email_domains = [ "*" ]
    allowed_roles = [ "prowlarr_v2:prowlarr-user" ]
    whitelist_domains = [ ".hoareau-marion.eu" ]
    upstreams = [ "http://prowlarr-webui.prowlarr.svc.cluster.local:9696/" ]
    pass_host_header = true
    reverse_proxy = true