---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oauth2-proxy-creds-prowlarr
  namespace: shared-authentication
spec:
  encryptedData:
    client-secret: AgBcFkYv/KV2kHC5ysHv86icF73dWELnpln4g3HqrPr07Uru0DVi9IFmxB2lmVaVZTcLTO2M2THGozYpN6kUvwPwX6J0VEboDaxxe3+4miZL8XTBU7Io6chOIBVJpSEjiU3Zth5PwzDEK14egcc9sWabbFrrVCx9GW2XDdEPbHgh8PxvzmPcEABfSN8AEJwS+JaHSoBKuTURI4Eit2x8UNzar3/IuyF+MLmQ1V4wY+JEovtuHRXQxhm6xkezYRnDjyaDzXBai1xhOVAph2ozF7wejHIIm2UZOg1SycNegQWZ5pJNl4U17Dk6891LOrPJ+60V+6cwK42udZuyE0DI/uKp0uoVu1micZJrNuMj/yakAjIqgWxWJ9B79CbTnfIGFA7Nv2d8lbDDiTX9FgNc9jExR8w/6lhqr2Uo3V4/I/Q0rBO/PCrn+slHzqkFn6dI8TDV2GauNYYwVGXqfI3U6DhDQGbtnVrAQyz1HghVQ0I0nK0mZZ95sGVYLEcEt8HvqEq1kN4l6kjG+VhLUWYJOqqE8hLIOGR09WjVai9B+6GIVMA1Ug9Of7vbRkGC4M1tbnpHzjS+JR0DbQ6WX0NQnUP5HZxL47RJDYVhZKdpcJ9fFwsKWWmXkRiNEyCrW9xvt3Jwve2ASD94PplfLlhEdtC3gSEIGxd73/8CVEvsz/ATvQWN52aSfnKU5qQBIIhD0zlFRitrKwxdbgjXBJRCYn7Iha7PkSOQrJP7rkTy7R91/g==
    cookie-secret: AgBBZem4ko4UQQAXw4rs1+IpFKbplc/kphRYM4VWDADc+pRFkQgJtX/kQ3Oq+pyrLuzF04tHxQxSAC/2CP5csN620hTlHwrFpDq9WMMZL1f3AICRBvaMM2VWZQRFMXRou8moPnVZsODSxASJ7ogt7m0hPCn7vGew8y3HMSwG6Ui6EoLQB1tVvfk/C5aMiJxjtXZHB+BLlt+6E2DQXinwi64LONuinz5BLZ6xV00vcX+WtP/PpLyGNWeZ+RiBhYCKN95qnB93JIDrDcoYktDqZf+8H6uCrGhqe4GtsWaI5ZwbCMeHDtB+iUDy8wa7f0wlZvx3ZiqyxmJ9JzUtoKgKVOX6RCx5SrBpS5FgYUbbEv+72TwV9UmVvMtUVZfkb1+xETr9bkJORj2SGO2tK0m30T5PkgYNURA1+6qUi1T8jns+EAETNS9b2SGyZlTbDFiGWsAnfUCKSIQmGAcdvViFaLRdmM+uOsFJOTgceUxDwp0C55H3WYVsOVq9nWVq+9tIhYwRYciBTgvr9YUW6TbExdDvwLIgUxg+ZKoq0rMlFmZY2K0S5nRMWlbB/JITD2Awhpb3bY3l34ry5SlsWJB8Qpyekw8hurQ6vzidWmQL6+dEiloQRvzML+fFNZlguBSBbxXcfPHjZMiWVIqnk8w7Q+9pak3wRq8nYh1qsY0U3rYt23C/YpEUOc0UBWra3bw1GXFl+d2pIWv6E+HCxTBXTpqztJGhAlFp17OhW6T6iMEhM5aiw0/doFqj3Uc/uA==
  template:
    metadata:
      name: oauth2-proxy-creds-prowlarr
      namespace: shared-authentication
    type: Opaque
