apiVersion: v1
kind: Service
metadata:
  name: auth-prowlarr
  namespace: shared-authentication
spec:
  ports:
  - port: 80
    targetPort: 4180
    name: http
  selector:
    app: oauth2-proxy-prowlarr