apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-pvc
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client