# actual-budget/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actual-budget
  namespace: argocd
  annotations:
    argocd.argoproj.io/hydrate: normal
    argocd.argoproj.io/refresh: normal
spec:
  project: homelab
  source:
    repoURL: https://github.com/jhoareauamarion/homelab-kubernetes-apps
    targetRevision: HEAD
    path: actual-budget
  destination:
    server: https://kubernetes.default.svc
    namespace: actual-budget
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 0
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
