project: homelab
source:
  repoURL: https://github.com/jhoareaumarion/homelab-kubernetes-apps
  path: actual-budget
  targetRevision: HEAD
destination:
  server: https://kubernetes.default.svc
  namespace: actual-budget
syncPolicy:
  syncOptions:
    - CreateNamespace=true
