apiVersion: v2
name: actual-budget
description: Umbrella chart for Actual Budget
version: 0.1.0
dependencies:
  - name: actualbudget
    version: ~1.0.0
    repository: https://community-charts.github.io/helm-charts