apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-webhook-ovh-requester
rules:
  - apiGroups:
      - "ovh.solver.hoareau-marion.eu"
    resources:
      - "ovh"
      - "*"
    verbs:
      - "create"
      - "get"
      - "list"
      - "update"
      - "delete"
      - "patch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-webhook-ovh-requester-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-webhook-ovh-requester
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager