apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: paperless-ngx
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-client
