apiVersion: v1
kind: ConfigMap
metadata:
  name: cm
  namespace: paperless-ngx
data:
  PAPERLESS_URL: https://paperless-ngx.hoareau-marion.eu
  PAPERLESS_TIMEZONE: "Europe/Paris"
  PAPERLESS_REDIS: "redis://redis:6379"
  PAPERLESS_DBHOST: "postgres"
  PAPERLESS_DBNAME: "paperless"
  PAPERLESS_DBUSER: "paperless"
  PAPERLESS_REDIRECT_LOGIN_TO_SSO: "true"
  PAPERLESS_DISABLE_REGULAR_LOGIN: "true"