apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-consume
  namespace: paperless-ngx
spec:
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi  
  storageClassName: nfs-client
  volumeName: shared-paperless-consume-pv