apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
  namespace: devpod-{{ .Values.projectName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
      - name: code-server
        image: {{ .Values.image }}
        ports:
        - containerPort: 8080
        env:
        - name: PASSWORD
          value: {{ .Values.password }}
        volumeMounts:
        - name: nfs-storage
          mountPath: /home/coder/project
      volumes:
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: workspace-pvc