apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: sunshine-tls-policy
  namespace: sunshine
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: sunshine 
  validation:
    hostname: sunshine.hoareau-marion.eu # Replace with your backend's expected TLS hostname
    caCertificateRefs:
      - name: sunshine-ca-secret
        group: ""
        kind: Secret