apiVersion: cilium.io/v2
kind: CiliumClusterwideEnvoyConfig
metadata:
  name: sunshine-upstream-fix
spec:
  targetServices:
    - name: sunshine-service
      namespace: sunshine
  resources:
    - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
      name: "sunshine_sunshine-service_47990"
      connect_timeout: 5s
      type: LOGICAL_DNS
      dns_lookup_family: V4_ONLY
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: "sunshine_sunshine-service_47990"
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 10.10.30.10
                      port_value: 47990
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
          common_tls_context:
            validation_context:
              trust_chain_verification: ACCEPT_UNTRUSTED