apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: sunshine-route
  namespace: sunshine
spec:
  parentRefs:
    - name: ingress-gateway
      namespace: cluster-gateway
      sectionName: sunshine-https
  hostnames:
    - "sunshine.hoareau-marion.eu"
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            hostname: 10.10.30.10
            port: 47990
            statusCode: 302