apiVersion: v1
kind: Service
metadata:
  name: sunshine-service
  namespace: sunshine
spec:
  ports:
    - name: https-backend
      protocol: TCP
      port: 47990
      targetPort: 47990
  clusterIP: None