---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: configarr-secrets
  namespace: configarr
spec:
  encryptedData:
    RADARR_API_KEY: AgBwSC7Yq6yGagL7hjPcNRaCYoLFrV84UZNddPWGfTJgY8Ta3uauYS8xCF9SvvNHfQe9OuHc70qhDGFG+Z+gv+B5l/C8EGqhyJEs4qf5f2bP3IeT0ECHr5D2Aq93NWeqQynbKV/wpJIVuZoS+UbJ6ETGMZMpqA3en3i9jYAEq17B2PzvkE/AcR+40xgyk01pxP+3+tNZzummwbPqqW7oEhB9PYIy6QNls6bJoq+NpqH/hle9GpWm+XudkPs4aU5NWtzOAU1VpmYCkMzS0d/SL7HHp1vSjfKuqjeivPFL0+omDTQ2KbBI+zzgOrcz8jy8ohnT6Q9rB5t9EUOgDOqkn5qv2LTk0w9EahxnM824QLw7AHFLJFPd54jv0cf4DOHooyl+hpyILJnOQ3bkQpF29NiKAkfYgRNrFlW7FYKRhJ+ghMsCGYiZvZd91ay9DtzVlCSZqI11FgZtSXKLZJFo/x5vW11+5Vw6EoYT7/EDnvCLtTrahd2ZfPVyBfV6XrBsw6RaYdkF7UdmkxwsqIVK2yGX2HaoQ6aAnlsdrCRx4ewZYqGsEmSikmNzspDE5DI8rZIRLKZqcek3Le5v315d+j1EbzanHKlrpq8cN21fmG3Pg6OBIT41jBNjzrOmBBrTxxh8ypto2C3jzwz/FYR03mz/fg8qOPw+x8ZifXwv0++HDVcuSIQI5am6MW8FSOnApmnoyKxekqzAb6fcLyNNnKmyMnisXaGp0JNktNgw214OZNslzHvze9cls/nl+w==
    SONARR_API_KEY: AgAi64rkk0YcTIjNpyB1+mZvm9rvq4IcPkz3VO8M5SUsgU3q41Khy8Gx6h5kj7KH1/kxSmKO4go7aGz4IlPkVJhLlTClg7yEXEcXfzj72O0AtjRC8HqhtS0hpUZhoDwORIPyLiXQWgbMqjOfZFeRPvR0uVQ+pZbclpQqAdm8T0zYkDL6DTjH936cHPvhO79lH9mtud9rgCT2u6etbUFBZ1zGSoa0IWBSY+IACC/4WKzi6ftAA3xPEA+VQPzjubiGS7fStb9xhXjCoAXyuVrVrieXklcQi9rT13UYcfLjTRdJdvVJ6P7tuFN1Jm9q5t7weEfMEsXf9gQW1t66XqH6lZ2LqpMWhdJtBRPN1hoQEvEQ5AwwYBqOLmof1LldHXCcBUdPbLyFk8KFvOv0CyIFziialCdcxjffZyYwA3w7UEXOvwoVcDYOEGXQ0JIAEzc8BaMflr/6zAqwL112TGlmxIvaxQg9b72Lw8YV+RX5+lSEIqzIlTk7dfmeKc7obxH2fvmDUt76+nuW1mZsmnEP22TxTVnh2gr+knhIVwor/X1VaTcoKBG+wd7M41GaMGBi/iSzkl0MOGzMiWxSP5rXlI3wdGd1cAh4yH7tlbUCceqhyMTj0Hgh7Gp5SfJtxka9mUJ8LxWNgDaDJajGwTBMQr2V4AeOVJI7vtYZf9ynXaQznFUcduYaQmCSHNP812Saecy0dp8v4hq7VntXAEv5kEFMnerIoVdQTAydhjHRzeLA4QIOgVsGiYHL83L+ig==
  template:
    metadata:
      name: configarr-secrets
      namespace: configarr
    type: Opaque
