---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: configarr-secrets
  namespace: configarr
spec:
  encryptedData:
    RADARR_API_KEY: AgBa0DY6F91WC6QUbbwKC01K5d2ZERW27Tx6QzMqUVLHgOT2i843BijFN1pZJW0LaiT99bboSvjDAOqMdrPF1BdLfOXYbiocSvp8g9giLZYywjRZpzoqArYAHE1ldoTHjSCt4pY66IG6rTtLG7c28+Ns8+HuAXeQhkUCUv2pEK5aRm6N/Tm1Xjhf3H9mPRyfEU6AYTyVBANLgSXLR2yHcRwuEwfqLSM+xxV51qQax/gk1NcUbIo8q4+RSNL1E3OovB6ZJlCkUSb+q9h5I3iJdEajnOTYe+UKc7zRWsWPcRoYS/1hRP1lMjd6Cw4wzDRef8OYY5iizFZQaXTiSk4tmGHftosD7QSXmrvbyXAF6wJKiMc/aipXbnOrWvSPIuViED/bDo6Rz6CLzAabEe/M29ON/Qn2bw4+J5C5kKP5i748sjVKI5itc21A1IXxwgqhmQrfLadtHE+VbFNTGOBVNyOc1EuZGMGNKYyEEiWrbxV+D3Pkf9A6FgOJ0KUCHG7udTJyzjoPEb7soTD/L0kUcJg1NE4GveYzOI0NWa9maFZAPa8P3HmT7wEY7lb6/jhmjmS04mVaoMmaxqlU47MHHK5IL2mt9P+q59dUdea3UObk4/hWP5tJbL6kuHe92nAwdurlAamkCW266J1kepzQLiIrv9ImN4YXTX7xWnK5fCrsf9qvbIQQhGOdCwhP07a3SjLJP/vDFCg0Ku6r6xl/pzu9Phxn2Jr+88ZlHPEFs7DacA==
    SONARR_API_KEY: AgCjvJCSJ6EMbXy7Yc3gPC0T3P/0qhuXqDuTwNq09gZnMIbsmb3bK2Uodg2Kg/Q44u3d7yuWEuCZLoKavt1eMwb0uJXjvswtqrq3GkLB3LjletR6W3jBk9xIr9xgNZEXhsLiosQ9chKNWyNSGGFmXsJey/jqbJlyL+L+5TUm5HFrprem2kBG6EFeLt/aAySsf7Q7hs53XelbMFMu2B6/2o9Vfih5Pxd3JYIqWivmxAapIkq/olWIR93XTZFTWkR5vYCiill/26dLml7w/qe7/7E0Bue2ioLjWZBjGXWOhw1Sdf/b5FXHMElms2G9iTjxic1QyJkPSY2lJcyvrEnNb3FI7Utj7S23vE+7AjCku37XvVllNq3WnCXAA/lVIlpuqZBr/8z4yK9J3kHQzqO84xkPHPj1+U0HR0DDlxtipDqGa6YNkRr9gT1IVCK/SPBtR3ZxgoBEYucvl0SQ6JZRvA5VHv/EAeOGZshulfClIjlFHkkUD6GjzhC7hsJlnksfkySSeIy8czAK9sfvHGDfHWjpe3s2VLjoWG5DGcIIU01CCeSw7fON1vZQae27UcJxKq9D2jD1K0WC+gfM+UYIFz5sLVdac42nagHpbhbqYUHvSD1/fS4Qk87LNX42rZ/6rsgOI+HFG+AYCPx1Btvy4BwXsNz58Ic9ueCMkzLJfxhCcEzn+NiDxXpF7j/7SoY6mjvLUVPBJQnFJ2qGRrBOgbvnVZSw3hWNQ++3kN1F9u5aJA==
  template:
    metadata:
      name: configarr-secrets
      namespace: configarr
    type: Opaque
