---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: configarr-secrets
  namespace: configarr
spec:
  encryptedData:
    RADARR_API_KEY: AgARABEo9X+15h32xjdwvxESb8X9XDXEvbX69NzPbzx2HdpPcpNWOy2nf4dYZtycMqIhx3a9qyGiBVfGPc2SVkxT7d879yhCF27FTG1or1avQKQYI91kKV/LJ7KhfUwgqPA0PqtAVkYmzJEJdYypiReHgPv9rCS7ggyBS1Kpw6wF2b37KwNdjbnDn9QtQ/Zb7+6SOfhOGDwC6mZtRz1011chgGixriATSeJTAfNWY+kSTs8+MpahoAndnii66Bz9zpNh2+Yc3Vj4JaC592knk0XlXrk8Q5lwIcfUuByKPzHalUO5HgK/1LwQ2fFblBnJq828qq0Ve4DagMWBrbo+cZuypRymdUt4HLXWtHKRfJBgWaijk1YPWC67zKb93Tfe2Rq3sLUIw8EXUP88f4C/+MCcrxxiQnLFkSfmUZ+iBQA8uSvBMMST35eTU9Roq+zNa6kjvL3y7uOljipjez5jVgVIUQEMdzEpZ8jF7Lahw4SnCUlrDwhCPJAVV5RnzVdK7KKXLAWnmSxCJyquWbJbWHjM6X9ujupCjMPFDZz57Eah3NppGbuYAIrwqrYGxrgx3SOrKt3whmqGOY/svhFcJbcTbfhbYaPQkyyQpylOu93ch4hWv3oNhbbQa0z7LK61HFKEmEbf/y8Ojg3KZCnzGzwzMk97za19Rhst/WdQu61h1gffX8gxRwLZxrTM0/E5ZoaDd43Uu/rRf3f+51mQEb7dylbwTPIIEtL9tqFkxBAxGdV9WpY4xTu4wWQMdw==
    SONARR_API_KEY: AgDAJqPSUA9VKa9L+bxiQuZ1bcFXvYuqoAH90vtDwzf0UlFIcitPiCrLomJUApqF6ME+MCm/4Mqbz7JgFK04tqHupZwZ9ngLGavj3YeE2siQtVc8ommeHI3lTMUcrhsshg2dhnmhwBA0JPhVLdLGakAKh7wLjyMXazu2EbTzaRqym4YouxtPHdxMgBGPyGFXRHAwgfapCdxuKp5oVVnmccq6OnfpXseAXLf90MvESHFJg/ahXj8/D31x5s2RgAwaPpsdH7W+gubrvSl54fZCbVXACDJepPHphsLXBgGBvWGaXmEG+G2NcIxV9pPBaz7Y+uZlpGjzCSPE2fAmsDD0PoF5AgKMXhp0JDpDghPE4hKcd0IUHrjyVPUIaNtAFmL48WMqZA9Z29nSLM4MUsv26FM5mfetSReigc5eL8kYd7BFetud2JD3p6l6VKVhpMw5AMEoSLNr6w+yxxPlXqVinJE6rKgWw6B0vnFia/lph3YlS0wv/6NtepOxbVL9L8ZWQ9865Xdaoj+JrgTr4gvyhVbJubIVyEirEjCZwy3X0S2XnpbizVYG9sZzO6aPRzBPxfhXbA/IKYFFduXpUKphtVcKD7QQLYQ+z7PLdNy0T+qU5qyOjfBVSav8TNqGABnAXjW098cp6v+bjLKBoGFRHeS9BoBJvvEfN/bIkgCfEUQ1HjEy2Owmxo6ksXO57p1LAcNFzccGKOJfdsNm+YfnBAwbU/f4wigm68IM68JAHypXvUWp+pFodJfAqERwQA==
  template:
    metadata:
      name: configarr-secrets
      namespace: configarr
    type: Opaque
