apiVersion: v1
kind: ConfigMap
metadata:
  name: cm
  namespace: actual-budget
data:
  ACTUAL_PORT: "5006"
  ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB: "200"
  ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB: "500"
  ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB: "200"
  ACTUAL_ALLOWED_LOGIN_METHODS: "openid"