---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns-opnsense-secret
  namespace: cluster-gateway
spec:
  encryptedData:
    api_key: AgBv48WcUR1RCUQV0Zo29My2h5DVrMRd6Ybl58F6bxYc3b1at934wIN60++zumj40qO+5KpjHSCxpXdejBOSqR+EjrGNil5cTAvGrGM82xgdkJw/5KQQnZ1aFMQ6JzT3hTO0BtgXMuf3+WDwQbZ4ByhB6AtXgFkRiBlOG+nUuLh161ZFD+2Yp1//b378pn2EpipEFgqXcvEK/sldntjCVlbu6N1ypBZK/6MpFr8HzjzoXra1MQD7si8T0ck6cL4kWPpfpgBpe+nMA5z7wbNseByAG4g9t4Wu6IBn8pTUiz29CWfMAXKi3zWMCk9MfN0fTszziCRNsGVRhsbS9CFrGQ+5doy4RSkn4vvWFmGBkxWb6hNX+CoXYg09TJ5eZ3nDTcE7gWRUa23U9ROInHeugEC/jfZSLPzOX2/+dCsjnRBEL0anBrli9eWaAqTomcTxfbukSe/+1/8quN8YM39QC0B/+YHU6J0h3q2Xg6shd92xDr3kFgaAbP8uzvpYh7E7smwe8pkGKX9znyjVrJ543Awlbh1oY9bAhEkPICY8jivVvvg2deNUevuJYUumMfB+JLPypPvfATc3LEf56RO1qF2aYK5+/AV6KapCv53NuLrhEjeqTGhWx1f6cxUb93q5ShL0WGN6KqTnbBTdnMw4Y5gm6oL7YFBEoj2zjRaboPpaVzwiiuIVhFyMnVZcWG2W0wIzGcJao2v1MYE+d7WYSW0LvFrVKWA53tScZ1qLyhdBBSnBpUrFdXzEauxzXHnpzoZF02Wp8neG7FyVmCqFpwowO9YlemiMfkzCXZiUJGQzjg==
    api_secret: AgDVgo3I24qAcUx9fKEsIQWAqKN875coM4Q8b9nILQNA4ZoUAzGS8kmBKgYatZK+v0e2z6KwKgEQqUwTtBRoeTp6tZ1gX0da1f3W5xZkbESCeYogu3ut3mtKg0+tNj8wr9Wr9vcouRoVsS4DlYEdW5jpj4/gD8PkbuFJhvnMl6KXMnNy2ZcCouAhZDMcSZkS76xqp00v+/IrjSdQyMSMBVyIw87LSDhtGQivWC7TU7Fse4XKZMQe+o6d+F/YZdUR543VMxU92Xy9WQvwgojR3EvSzTnudwQ/09u7fRPyqGcLH9UR22IvLIuNOwqfgLjv7+j8imMzcs4aQewCF+HW+e5hdIluLj5cxt4Nhtv3x4V+FnJ0g2cAlaDAjeeHLkA2SVjFKSQhC/DHP0Z1xgO3K/1P+YsZ3L+Suzo3ylepURmVNJJnqAU0hFMp72VSPqeVMNqB41OzlQ+wCTHNyVxkVllc7YPGY5Mz5CRsfb8b72usazXAMISAHUhctWoI3AqrddWZyjRRBkKJyBRBhAdqexvXpJr45B9ZuSqpAunaaJyaVhswGPxD7eJ7PmLsqf63S4pcB+/IxVxwbJcTseXyZp3LC2v1fCs4g2/d+IJoO5RqaKRajQm8uUIU8UX0FtOEm+p1Ks7hOJvkg3oD25Y6/6fxWy+8dr95ha1k/sAKcJpF3iZG5BaVz6qRBqKfpxUXNvhl6IripqxRU6u9S1aAIpdQ21lVh+Vg5va83nrL9zbV+vv1PtrH1dAUnZ92xDBYDgJkAQNzf6FLoMxR/1Fpzj7JRYAI38gj7x46Sb4mM8ZbWA==
  template:
    metadata:
      creationTimestamp: null
      name: external-dns-opnsense-secret
      namespace: cluster-gateway
    type: Opaque
