apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: vlan50-pool
spec:
  blocks:
  - cidr: 10.10.50.96/27 
serviceSelector:
  matchExpressions:
  - key: gateway.networking.k8s.io/gateway-name
    operator: In
    values: ["ingress-gateway"]
