apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: vlan50-tcp-gateway-announcement
  namespace: kube-system
spec:
  interfaces: ["ens18.50"]
  loadBalancerIPs: true
  serviceSelector:
    matchLabels:
      io.cilium/lb-pool: vlan50-pool-tcp-ingress
  nodeSelector:
    matchLabels:
      affected_vlan: "50"