apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: synapse
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: nfs-client


