---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: signing-key
  namespace: synapse
spec:
  encryptedData:
    signing.key: AgAkWruQT/yFWOtfBPnrFCFHOdNJOhVWoMCCQK+tz3od96HNpfbwwCBwxfDlCKYPYd5wsXqXeNsR5Vvr4kARxJLTw6pz50yWEfnS3HyxQQwLsYNC1DEf+lc4fmUOY/wred+5p2FfT6+7Xlni2JOdIi3UmhbRleBNLf/vRZddelJqF6JbboYbLOxQzwQqHx/kAAkCIF2Eqyur+yTAgKvto30gWtCqHX2i6IlvNW51UmG4mqReamWZ1odmRKLv57oQGvLz7LJzA1D9QSRRdybRuzv7XYZqBjN/JpTeTx5R79J3OE4ioKxJ1d3vjIeAZ3A6W8l+vKsciUN1ZhbeFjYOOXVazCbuQbYQJDm5VkiiJFIgv3xm1s9UfvW37gJDoPSG8rnIpIxsfgs2gUoTveGyOVzV8UWOoo3JyBDxwzCmjJ10/VaRD8oxiKkbUEZKxzZ1kl2uuwuPW/7hgnUGnMHlz0UoLpyQ0xlNWd+FCUXqxG1Kzxz7KS3RF3oUsowj7sb8gwvn3YgGKkDGzKWkJE19gJ2O3Rn9QnIaMlVxVdkNeqZwwG0ZQHJ+yZE/sQfs6eb92Qq8F6+TPCULpojT6KUjacSwWxuYWbbGe6a6Oq80/w9mjRjcI6lHkBvuwx5ocT+FM9rkHCPkgAZwOnoGlu15KXOUNicgUFzlja76VcNSyUxveH1gdqV70tHJbmA+ucbgNkQhRfALFGUmBZpeVGvjOOs1GLw0N3iK49rPR+vDYA7ds6kTRfxHziTFuifwky4DgMQ8gYQdQBJ4z+JpHA==
  template:
    metadata:
      name: signing-key
      namespace: synapse
    type: Opaque
