---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: signing-key
  namespace: matrix
spec:
  encryptedData:
    signing.key: AgAFgPHVP4XEeBKo1S75lGgdh5GMcP2S2Xt2Gu/BXKo1ppirEa1l19Wxe6Qu/n3cEGIaiyd+T+ME8SVE5b7LWo2jvZWUiDGcdExzTdxQSzip3ZOy9n6j5TqYdIpTC5Ru0ylelCnA0wXAtn7pgHBSAirHgam7sGpGRuQGq+pD6Zx/t+fVo+O6agWF59bnYYR/FMT3apWLsPerBhXUXvwjhThXPc4XEx5scRitYyG+ReBmba5RGX4uAuM+lTpWki7Dy0G52lUjwwHAzZfjEh8ejweOhiSqYy6asEsXTgFIn31CIAe0jmRyckKEFqwuGFENJz8VaEAm3K/bFUqCKFEikH8ChD3gxzkSYKeYhGY4VYCbwnP35BcPUdCRzMidptVxYpAxnHtxYoQyL+ta9EbehqxLOLFDXuR0O822O2khT4CRwh3GzqcmxwEzabRiDJWWkzumardYWO1aZu1GpwxGRQxAoSO8ahIEBgJ0EiCDO5D1jp4A5rHroSl6UKlXstpn+uuQzSOQrbuoBcd1/e6aZcZZAppEi0HmH4ZhaFN+WYG6pH+fttiKwUooZSdK5Msxs2RlMBGtflhc0KQWS6A5bGrd6QON05VgxNGpLfHjtD8gKGA1j84VKztdvURRtPenMb5naVF+fLAOFUIgX10PPBAz4komsNuwGBXsfgGBhbi3lrj4Fv5RLM+8H3eVHUigVH4powyMNx4vWT0RWN7IafaOJ1HhRhEM9J3t70QK1d5lfHh1RrbdydsSp4uef1eq0dgOAWhodrQiMGIAyw==
  template:
    metadata:
      name: signing-key
      namespace: matrix
    type: Opaque
