# pvc-template.yaml (Example of what you want available)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: devpod-workspaces
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs-client