apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-cm
  namespace: sparky-fitness
data:
  SPARKY_FITNESS_FRONTEND_URL: "https://sparky-fitness.hoareau-marion.eu"
  SPARKY_FITNESS_SERVER_HOST: "sparkyfitness-server" # Internal Docker service name for the backend
  SPARKY_FITNESS_SERVER_PORT: "3010" # Port the backend server listens on