apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: sparky-fitness
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sparkyfitness-frontend
  template:
    metadata:
      labels:
        app: sparkyfitness-frontend
    spec:
      nodeSelector:
        affected_vlan: "50"
      containers:
        - name: frontend
          image: codewithcj/sparkyfitness:v0.16.6.3@sha256:554feb804a1c1a2fe2f1b0a5870ad9b43864a4c34a1be4b74d66797147659187
          envFrom:
            - configMapRef:
                name: frontend-cm
          ports:
            - containerPort: 80