apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: sparky-fitness
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sparkyfitness-frontend
  template:
    metadata:
      labels:
        app: sparkyfitness-frontend
    spec:
      nodeSelector:
        affected_vlan: "50"
      containers:
        - name: frontend
          image: codewithcj/sparkyfitness:v0.16.5.3@sha256:88d9412d054e9e44980f7cbdc41c28652051bf4a4e663cc49b01b4bc3cd8e7f3
          envFrom:
            - configMapRef:
                name: frontend-cm
          ports:
            - containerPort: 80