apiVersion: v1
kind: Service
metadata:
  name: sparkyfitness-frontend
  namespace: sparky-fitness
spec:
  type: ClusterIP
  selector:
    app: sparkyfitness-frontend
  ports:
    - port: 3004            # external port
      targetPort: 80        # container port
      protocol: TCP