apiVersion: v1
kind: ConfigMap
metadata:
  name: code-server-config
  namespace: code-server
data:
  config.yaml: |
    bind-addr: 127.0.0.1:8080
    auth: password
    password: ${PASSWORD}
    cert: false
