apiVersion: v1
kind: ConfigMap
metadata:
  name: code-server-config
  namespace: code-server
data:
  config.yaml: |
    bind-addr: 0.0.0.0:8080
    auth: password
    password: ${PASSWORD}
    cert: false
    proxy-domain: code-server.hoareau-marion.eu
    default-workspace: "/config/workspace"