apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
  namespace: code-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      nodeSelector:
        affected_vlan: "50"
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: code-server
          image: codercom/code-server:4.128.0@sha256:bd4a3a022ff016954bf9ae6ea0bce6c7eef96a69da4d2fe34552638f32d4820c
          args: ["--bind-addr", "0.0.0.0:8080", "/home/coder/workspace"]
          ports:
            - containerPort: 8080
          env:
            - name: TZ
              value: "Europe/Paris"
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: code-server-password
                  key: password
          volumeMounts:
            - name: config
              mountPath: /home/coder
            - name: config-yaml
              mountPath: /home/coder/.config/code-server/config.yaml
              subPath: config.yaml
              readOnly: true
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: code-server-pvc
        - name: config-yaml
          configMap:
            name: code-server-config