apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
  namespace: code-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      initContainers:
      - name: init-workspace
        image: busybox
        command: ["sh", "-c", "mkdir -p /home/coder/workspace && chown 1000:1000 /home/coder/workspace"]
        volumeMounts:
          - name: config
            mountPath: /home/coder
      nodeSelector:
        affected_vlan: "50"
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: code-server
          image: ghcr.io/jhoareaumarion/homelab-kubernetes-apps/code-server:0.0.2-renovate-docker-io-library-postgres-18.0
          args: ["--bind-addr", "0.0.0.0:8080", "/home/coder/workspace"]
          ports:
            - containerPort: 8080
          env:
            - name: TZ
              value: "Europe/Paris"
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: code-server-password
                  key: password
          volumeMounts:
            - name: config
              mountPath: /home/coder
            - name: config-yaml
              mountPath: /home/coder/.config/code-server/config.yaml
              subPath: config.yaml
              readOnly: true
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: code-server-pvc
        - name: config-yaml
          configMap:
            name: code-server-config