apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
  namespace: code-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      serviceAccountName: code-server-devpod-sa
      initContainers:
      - name: init-workspace
        image: busybox@sha256:fd8d9aa63ba2f0982b5304e1ee8d3b90a210bc1ffb5314d980eb6962f1a9715d
        command: ["sh", "-c"]
        args: 
          - |
            mkdir -p /home/coder/workspace
            chown -R 1000:1000 /home/coder/workspace
            mkdir -p /home/coder/.kube
            cp /etc/secrets/config /home/coder/.kube/config
            chown 1000:1000 /home/coder/.kube/config
            chmod 600 /home/coder/.kube/config
        volumeMounts:
          - name: config
            mountPath: /home/coder
          - name: kubeconfig-secret
            mountPath: /etc/secrets
            readOnly: true
          - name: kube-writable
            mountPath: /home/coder/.kube
      nodeSelector:
        affected_vlan: "50"
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: code-server
          image: ghcr.io/jhoareaumarion/homelab-kubernetes-apps/code-server:0.0.11
          args: ["--bind-addr", "0.0.0.0:8080", "/home/coder/workspace"]
          ports:
            - containerPort: 8080
          env:
            - name: GIT_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: git-identity-secret
                  key: GIT_USER_NAME
            - name: GIT_USER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: git-identity-secret
                  key: GIT_USER_EMAIL
            - name: TZ
              value: "Europe/Paris"
            - name: CODE_SERVER_PROXY_DOMAIN
              value: "code-server.hoareau-marion.eu"
            - name: PROXY_DOMAIN
              value: "code-server.hoareau-marion.eu"
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: code-server-password
                  key: password
          volumeMounts:
            - name: config
              mountPath: /home/coder
            - name: config-yaml
              mountPath: /home/coder/.config/code-server/config.yaml
              subPath: config.yaml
              readOnly: true
            - name: kube-writable
              mountPath: /home/coder/.kube
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: code-server-pvc
        - name: config-yaml
          configMap:
            name: code-server-config
        - name: kubeconfig-secret
          secret:
            secretName: kubeconfig
        - name: kube-writable
          emptyDir: {}