---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: git-identity-secret
  namespace: code-server
spec:
  encryptedData:
    GIT_USER_EMAIL: AgASkK+llkxh+Nmkhh6tfGtMS14nJdyteEZFtAHcQtLJgqIXOk9mr80JoBOqes33wixAm5qNhvbyMD02HTPVZqfYE4W1TjxOiSYkO3t31iaRmc+ATZaWNAXJ74e5IQ+1LqS/grDpKdjigsXlayzgZUCzpIGXt9gs+1Lt+dVeb9MTS9DeCttYzpt/ZAF0ThIMCRmZL3pCmnwZoV2BN7DBZf8oYZOhzlPUFwtmxDWlK809Rc4upPzsMolLz3i1LHi+oJPSc8wVN0Kuyb46TgXGwD7lwT/ASyFbOkqMKkKEuF0zci5x/abfiQ/NgQyVS/YUnYi0jag595E/zA0hFOnT/CuyLT0g4qPQvjEREGt+jF2WcW7eaqoZCyZGTxFojZdnXJs780YFOPV+sYUYaN8ohBeHBLpfalVhIm8vxmK0CBfIhFwXvM/zXZRYjHvqFyiZakWmE1S+ENwUZMFmPvbiuZirazAuxyRJtCi1S1rstEkqmLE9DRNsXhtihfFZYtG+pyseiRp7k6IYocWY9zdehCf/wUcXedtoqUkFQ9XwYqGX39UNOnjLAEg/0yfYfVHirjTSXn1/17eDfQkc9zSPi/4oSKafbwvfOIW1pkl5Knbk6mkSu7J4729cnMw4dxxeNM+WHO/YqNgALg3JNMXwPJfWHEHpQRIdvIZewfLqfDqoiysqnOFOsvzY1lje0xZDsl0cfyacNzLIhcPxMn8YfbQWRMDag5Ls
    GIT_USER_NAME: AgBmKWiQkmFTK6P9UgD9ilIk3/DZyIQhKDF5VdOtgflgbwEodtM/P/d+5SlcjxeUsOc55dTHbds0b6LQysrXiE6jEGIK1wAIRas/oXcilKlw8UHlJGt3e6LjTXUAdHnF4eq/yju6VRU8WcuGFp352AMM5qkv1sVlegY5qfeADJpJigl3CsxzpSLDqUY55dU2QrW2vNG5DQqBlxeI2xi50fUAvjKWfFcUD8mLMYhArJ9KX8U8Af55S8IYeVVjpWpYPOM1Quzpze/A5wEjRU63T4ltIw3X/VabKhCT0ZrRTIl3TBUm+8KDVDln3vj8VoWBJCEvFgq4FhmE5RMSxQZqwV91VcGgayD5Hax3KWGBlx11i8nzeW5o4yOzv00Qs+VCFxr+PIZQx3kEB0Va5OgAn4wWcm1cxvxEcrBpO+TR8XtGBPht9oksHoL1ghfr1VsWxoLazHs1jgVfyTUGpq3Wn5mjHHa55ok1WuqqhHrgUXbuyLYaV5TvNU+Xib3PrwymkHhrjYgGw98ofdgpgy7W4cFs79Z5/nMEczVluN27u7EGLlsjMbwHZDBKfEjhXn8e/PC2ks4cE7IrqaFDw/kvTQR+8NNhnjD1XCtGVX93Z2BtLZubyfuDhRO3h4u+T0+LLE/o+GRsFWZ1GRNBsyXZn2TIAvi9untHRafwY+79AV2izyszgMChvHbF6J09gAlZPppmJwgVTZuUEU8PpOIpDZis7ZaEsPg=
  template:
    metadata:
      name: git-identity-secret
      namespace: code-server
    type: Opaque
