# apps/code-server/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ci/helm-chart  # MANUALLY IMPORTED FROM https://github.com/coder/code-server/tree/main
  - my-configmap.yaml
  - my-service.yaml
