# apps/code-server/route.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: code-server-route
  namespace: code-server
spec:
  parentRefs:
    - name: base-gateway
      namespace: cluster-gateway
      sectionName: code-server-https     # Attach to the HTTPS listener
  hostnames:
    - "code-server.hoareau-marion.eu"
  rules:
    - backendRefs:
        - name: code-server
          port: 443
