apiVersion: v1
kind: Service
metadata:
  name: code-server
  namespace: code-server
spec:
  selector:
    app: code-server
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
  type: ClusterIP
