# Extra resources (e.g., Certificate)
extraResources:
  - apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: code-server-hoareau-marion-eu-tls
      namespace: code-server
    spec:
      secretName: code-server-hoareau-marion-eu-tls
      issuerRef:
        name: letsencrypt
        kind: ClusterIssuer
      dnsNames:
        - code-server.hoareau-marion.eu

  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: code-server-pvc
      namespace: code-server
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 20Gi
      volumeName: apps-nfs-persistent-volume
      storageClassName: ""

  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: code-server-ingress
      namespace: code-server
      annotations:
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/cluster-issuer: "letsencrypt"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    spec:
      rules:
      - host: code-server.hoareau-marion.eu  # Replace with your domain
        http:
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: code-server-server
                port:
                  number: 80
      tls:
      - hosts:
        - code-server.hoareau-marion.eu  # Replace with your domain
        secretName: code-server-hoareau-marion-eu-tls  # The secret containing your TLS certificate