apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
  namespace: keycloak
data:
  KC_PROXY_HEADERS: "xforwarded"
  KC_HTTP_ENABLED: "true"
  KC_HOSTNAME_STRICT: "false"
  KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
  KC_HOSTNAME_BACKCHANNEL_DYNAMIC: "true"