apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
  namespace: keycloak
data:
  KC_PROXY_HEADERS: "xforwarded"
  KC_HOSTNAME: "https://auth.hoareau-marion.eu"
  KC_HOSTNAME_ADMIN: "https://auth.private.hoareau-marion.eu"
  KC_HTTP_ENABLED: "true"