apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      nodeSelector:
        affected_vlan: "50" 
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:26.7.0@sha256:0f198be292568439d700cdbfb893e69a6009bb43a94a06a945b1d3d506c76b13
        args: ["start", "--http-enabled=true", "--hostname-strict=false"]
        envFrom:
          - secretRef:
              name: secrets
          - configMapRef:
              name: config-map
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        ports:
        - name: http
          containerPort: 8080