# apps/keycloak/route.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: route
  namespace: keycloak
spec:
  parentRefs:
    - name: ingress-gateway
      namespace: cluster-gateway
      sectionName: auth-https  
  hostnames:
    - "auth.hoareau-marion.eu"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/realms/milkyway"
        - path:
            type: PathPrefix
            value: "/resources"
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            add:
              - name: "X-Forwarded-Proto"
                value: "https"
              - name: "X-Forwarded-Host"
                value: "auth.hoareau-marion.eu"
      backendRefs:
        - name: keycloak
          port: 8080