---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secrets
  namespace: planka
spec:
  encryptedData:
    OIDC_CLIENT_SECRET: AgBxcVGK0dKE3z6fIk7HcXHVGkGnZktS/BH/vZ+KRRtgE4RezGJAwvmeAMr14yppGsKg9HURJhpArTkiRZ0IwS08DE++hZuWsrMmfKfyjKU07P0v4c1gk3OGjgt1XL7JcZI0WleOscFRj6Z8zMM3B1GkF7zRFogd1HCZaynmELLiyzz7iC4WdWSlNO8bedH2cI/Ug+ts5tJcyJgsOu/GcjItRbqER3J8jX0ERGwEGn0mWYJ+Q/SDMTF9hE1TZrzN/5nAiKHFs6uZoABVMLiLnYnY3XAgDXkIFQNJGgoMKmOyUyIGmvp11+Ytg2NaQPRBbk9ICxsx/211Q/4mdUqD79eaktuh/SZbLGZp0hv5zhOdWDgbhyBmzmNNG8kgy3LaJ1XlvYMzQ5QPGNtxIHuKm2eZUDIuDFuOIdLX7tKeoHKV1+CYSnC5LA4KIypq+V6YU8/gTxv7SaL6iLfBAPoCPlz2SDuOwshH7FtHnp42gwkGSsVFih0X+1GIYPBTnMSSLRd01LdW3LSrlike9v6cbc3Vn8kbGr7pwKeZ3TbyhxcqccfoRbqGmpFckfrC3+TTj5wp/d2ccBYx5DBqEfAiiCG0ImRB1wVZf7/6BtbEqlgJ3C38kB9LnpwGVNRfFgZPlyouZJKEEZZDla40fw/ZgVcvmyvSjsO7XRR7kgtQjKqfK5mw9bzJ0SbxH7NFH2WLj3WPbcZd9EPzaAzXfNV2IFwt7netV2gfH1Ec1xqknkzGELdNPXVAJsiNs3b/3BPMiT8//h8idRjwvf1vfDN9zjVpu7R7HtIk+oQ0vy7rC7lvPXT2GREtAA==
    SECRET_KEY: AgA5nvkP521if8QDF8twTQZCs8cXuBLFntLBvj4WDBNDbgjBOd4GcmZO/paWsT6f8xWFY6fml2/djqpgl/9affFlrA/FW+DljbkcuJduJYLplxBwCyPQfavEv9X0OL/vT8F02IkoWXNCXCVgo0VjUAbVjWJav0e0eL++B/A/53BOn1A/TJSuXpk7GvQHI5cbe5+iO55Vo+bB6QsO1fK9le+5e/2ivkBFdByFaGBbw5Exh8LJ3oa6rJ0tez4f/L0+8QE0dGZru6oKHcUmOmvD9VyoSSEQMVsOQqLkgHYfkgCWGfR7AqPolkM6dy+fC2Js2kZbRz2S4GLuFDPjMFwC5bRBT6MtJmmJz3sj7WA+CPRWgw+j6zLdSA2xeZ2mvIf1ZqQTranGtS6Dd2FLEuBTH+EXmxzXxicO34vAkKy0yn0yauaPPFo6k/WWBiwcHO++wui05GqEMaVv03VsvjndL5VtXNOHobM/IBbmeeFYIQ16M2dAHp+YGFkWxE7rSmYdzGTLrGIXLU+yme9fmpig8zkjLdMQVq23hh+tOKjgGdodHo/OGXDubzcETYTRqmvMjYOqpXoTaINE6x53T0hCl8Ek5j8V+Bd3+5kBt9IE6mtsV6xcO4ZUWls77hPh7evhGkTQHXkykYIX/KFs7s79fAC7+uiqZtALp9yZ72gmzosz3C3F9Tl/NWfzevJpjexbvTiNH7aTq2PxngiExBGOti2Ds/gk4RA5fZvUObxp2ionrelhvNzD25eeqxDrQuQkmA/xSZP9uF3WcbTdMlGtK98TNy1PJQCormGI/PKZaQAqmgzDVSVBCg9LNXFjZXuCu0EGo+OJdmc6l4ckYVVy/0GHqT3LyNsw5d5kqqCBOLqJLg==
  template:
    metadata:
      creationTimestamp: null
      name: secrets
      namespace: planka
    type: Opaque
