---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secrets
  namespace: immich
spec:
  encryptedData:
    immich-config.yaml: AgAq1cve3iehCLQywQCh1KhLJQC/bLUmHazWC848MFKtzbW4nbz1tT9ez1bjWIs4i3r77Mw6l+EvgXA3YMBnKly5Iuedk/g8B7Ekt0Kza13+GN5DpOX1vBrljASkhQwFY8PDVmoks9thQMJwJNmtLZadRBxBO29O/zI4694UIQ4pMIQlrb5rK5Y1mYxaPhPZz8Ma7+8bmFwxZaNAeYK0rws8K3v+FkM0vdGzXsQ7rWeGpsRd1gGgH7eL9CdNaOyy4hwbydCKeRg3IhuxBK68ndjCJNpjIQWia3jSb9DSwsSguxu9O8enIdHufnr37la6ScDVJ0fHNTsC+fXMY8VeoX7lNABfy8awCTl3zOHzVIIhfsODXv138EXWLxjLmPtUMoP8fhqIhW0Orj4YXhp2KdFz74chneyHAhRDD6fU6TUpC+NTiXRErruOEYbI6BL2/+QwcA0AG2leop1Vt2M+Y/mNp38X4mRAVbb/L1oojnQ5IHLcJ2zhc6MmQi2+ZzYADOYTpU/xsNzN1Lf3A+B7p44KifBhPl33aUCjUR7PNAZjLK2S4H6e8f0PPym2v8ZE/9zBFb+e7LhAWFYmKooYEsNoObw/kC+W5o1iRB7SfVbc0F89eMogTVzqvuWWBq/49DQ5TTOR29dNVfOkUAJ/it66srqDOen/l07Qs7w3sup2n05VV5hTKOjS7kRubbQPwbMp97HMLO+7fZh35amLQyEfFlE/mMozhkrndnMAHqAJ5ppaWtvp+/ynxVI5W7Fj1m7zt9Q+m3p3fZelOxNqQnoVAxoSCIpwJneXa2KXsXxAuMvBlscCD0YoxEHQVw4awz+/qbt3F0uApO68zSFs99ThlVpuKR+VIVTo21TLLVP36oGRcJnM6Gj55229gjg+VPr+gWy2VBeIIYY7BckuvGt3TZ9EKnUnqDh33LRVdKMly59ZKiia7CZhCkkzhi7KOGXGF9FCq//6ftyDiQtgiA5L+JUzKDPH
  template:
    metadata:
      name: secrets
      namespace: immich
    type: Opaque
