apiVersion: cilium.io/v2
kind: CiliumEgressGatewayPolicy
metadata:
  name: nfs-egress-via-node50
  namespace: storagenfs
spec:
  # selectors:
  # - podSelector:
  #     matchLabels:
  #       app: nfs-subdir-external-provisioner
  destinationCIDRs:
  - "10.10.50.26/32"
  egressGateway:
    nodeSelector:
      matchLabels:
        egress: "50"   
        node-role.kubernetes.io/egress-gateway: "true"
