---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oauth2-proxy-creds-radarr
  namespace: shared-authentication
spec:
  encryptedData:
    client-secret: AgBwJFrSEfOVpOQo0xNFjRegF/ZupgbasTANrKtPfc9CnwsNwgxIO1UN0LKtuwh9wNm/mskHSWBIDo/3f4s7CsRlFduobyAHb+PG2b+jq6ap3myJelbuvSH+W87zn33gF6N1TTpqZ5+gTsH04fqBXn+6HiLS+QYqfhmwQDuRKSvTn31YCc5meIcqTyOicI9bf5c6i5pIMgLN+BAjt0ijFO6NLi7SpEmyxtVjy0JkKknd4urz0xmIympuYaihTGBOo5wzxqiK0LvcsbfHPcL67qPq0dKj8LagqBlFeoHcCs0OCfUasPj5KuMum5ceiHvFFZ/SA1cRo9TAKoBSOu1AB/XINaGRyTFsFGBoGK5XBIVfZZOUUk4zb/BvpgaMC+S7ABTTPNL46oVcakUZWtYWfZA6qyoEZSnTDmDvve/xth42TOeDH5fs/H9Zz7KabyVeHEcf3J2oLo0pni3a/u7Yk9WNNEGsc0vGmly6EAycF0bzDTBMJYPaFJHwbpJL2G/txlCw5ZKCnJr23CBM+cmVbGVtBiEPhTo+ns/nPXE9INQ91v8kjm8E6WzJ5/bXqvweThqZ0jJOdhrNuw9cBdeCz9OcNhuRvks5+VUiGhrs5JDdL807ZwJQwFwwGNJa8dkVqoFcZfAh0EL1MYrUgasb6odU2mpgU/EAkjddsXu8Kg84nYp2jCh8J/CYQECJ7pmItjUU/hztQHcpr/5xrwDy/MzOQ9n+QOdifX5+ls+/UEEc1w==
    cookie-secret: AgAZRICjdeUKZKyZEqjk6mxnQ5rJRhUWcR+S95xJ8dWUr8OhQ2xD4Cl8vFVWB1poaZanmtoRCaD8VveJbSa7X7nlAlmz1Ossn5T/JYhII3gVHFWbFQ8TNycjdnsGXiBRqqfSWbI1EQ4hNbc03NY9XpIIZffBASbpZHIBON6ifP+4w6P0oTBfuTus4S4McOLKLZwPJEaTLBI8v9Dzn1ALqzSy0+6qSX4mPOQZDDpC53SEa7QqAKqtMb9KGRzP4/A3kbkYjFPyugQNk9vSdNwcMy/2NfLtD/VShGeLiPWKMt36AjyfoZ/itPEhqUxecvpibr1L8ftKIIttQRZxL1Pn7YSaeWPMR2unDyDucsk0E1c3nDfZPf2Hds7KDLh1xIbEZh1qP3u83u7+2O/PceMLrNBmya2ei8lviPGGIzR95ijJ2ebDlJCZsfbco+4uedHjqyOKDOgZ5zwcQNAguOOJ2ZFqnxKfvFj1p1wK1OW6rUi8huXg3pJ7t8fTm955ReLePS0ux5SSQ6KBhUni+0mCFVODssJTgCbeHVIafLQIou+4orndZMWyb/+gbSsqaAqcEUdgpu1SLI7e5X/LhPuHZ3ZL6Q4oBpgxBt95baonWHER/TZyVACsqVGTvtUyobZUhgF8ipnYhXj1+yrGyvq1va54RBqISGPoAOo8NIzOpc/uqvIX2UGUJPF+1Pm79Bye9ozJ0vrTIRG1QvsGOfX/qVnmt47KQYaFTcUrV/VbRHLpEJssCHrLU44t54pyinQ=
  template:
    metadata:
      name: oauth2-proxy-creds-radarr
      namespace: shared-authentication
    type: Opaque
