---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oauth2-proxy-creds-radarr
  namespace: shared-authentication
spec:
  encryptedData:
    client-secret: AgCOtilXjcm2X4pzCMeT1NrAb21ROGT32nIX1pUX+s20TpANTbI59a+OkPXCE6fTqNiH5QnsdWNlwR6KXpQIo5S4uBt4ABa3h9dPKqpa6gwVAy1ZtaVPTLljhPHWMVUXTWIc10ZfWJCr3Zg2AX98yLz8bjYDPpYpbjDRQxpyYRnZcj+n06/H8/5ZtS3kjGPxy0cVOVaGY60qKZAeJBXcalMQAZVz7ewF7vaoerly/POPiW3np/irIEviY3oXNYpWaT6cp3wH4/IVi5MsIMseb7r4b/VkfwLdqixkC6Rbk4MdMIvg0m+93XFrVW/30aD5CYtyrQyL3iA82AmX3Ou5qQgDJYGUWn8XFJFeH5ZubETFB/eozG8FlTmTMfugMwgulwgGLOND80ErZY82PbelJYtK+4gbF+xptIM4j2ZmqRfEAwWhk/yhhC//FutKOVwqapPJC/WAKFMl0xzhx6zX60SWfS+o6KAscao4AXnCAZmiuOoJ/bLrYAk+V7BgJX5231D1u28CVZD57C9QIDjlNRukCX0FpXKfWnSpofrFev7O6ABzA8b/XWEI91yOhnlLGIZZ+/jHf1GKpZxXrRvRgdLQV/w6yEJ9bDYHLgYr++3umtg/RuFAmxDtmXzcKlZa3XxaXpZBJwIflJsBCTa5OnrFWPjD1I9GTLTb5KieIJdJjPG/MgPStrz86QopKWb3u8vbQuhAuBGb5nSydSNNNbH1qFrQstenzP0LGQtw4P3lhg==
    cookie-secret: AgCLaYiZlDEQmY62NMlBbqCjbaTL3ziOnO02S7pxOSHN5KfBqC8jHWhGg/CaxKxf2C6gmEC9Y9w/GhOTMavhvnYRbp2WVLpUKDrN8MwhmSue+IQQzGEPzZp7jzYecKiDxldAz0E6XpIPMW4iILZr8DUAPTM6+dsV/Kwpdi9tKYkMFDoyGJT++O1oBFUnxhdTAasei3OgGHgD5uFcg8TcVmPXEOVRPLZglBPwnMtXIq2dojDcPmy4vmPXnEkk2b1j6CoGpYLLXI2TDpYAPfppaESsl8sY7mXlckJBBJUQBwfs4Bd4yP2RIwtu+U/0Vk1T8We8efZ7/DOXPxCO9QCCb/xwbuA1Fweq+xAZKlt4xEtZHTSbVIO2/bORWXv/Ea2w5zEqYyLm6Y/jZ4fs1P/fddXpHzVzZ6DBGMc+haJW6gXpsj2GbCrPhmu6gmw3hgdTmNMbGOa4G+0TUf0PtYIq4jxMSGxbavrAg3i8wg0LbHOf5b6vS/GQEu0Q2u+6AIZNjFf6z47WfA/r9Ig9lSLuoH6w4VlOG0P4rwnos1Dn27YLf/90r1neg+V/SNnkUrfbI6ADMUqpLm+DRVPTGDXMEuEkUKt1GR31fBC5hUaCJjmD6MXGpw4WajuhZyjaLKtaPHyky9LsScU2IkdzIQFqSDY0t0wfGstHgh/M3C70S3g96nJkjIhLpyHYhMh7h9vYv10HhJY55FFn7xRqw0OCa078F36W+yuDeqqDAV28zOjMRrSydeLImdz9CD1OuA==
  template:
    metadata:
      name: oauth2-proxy-creds-radarr
      namespace: shared-authentication
    type: Opaque
