apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: radarr
data:
  init-databases.sh: |
    #!/bin/bash
    set -e
    
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "postgres" <<-EOSQL
        CREATE DATABASE "radarr-main";
        CREATE DATABASE "radarr-log";
    EOSQL