apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      containers:
        - name: uptime-kuma
          image: louislam/uptime-kuma:2@sha256:a8610b3b4c38077922ba51b036691e06887d7cefd91fe620fd3d6d23d03dc240
          imagePullPolicy: Always
          volumeMounts:
          - name: data
            mountPath: /app/data
          ports:
            - containerPort: 3001
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc