apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      containers:
        - name: uptime-kuma
          image: louislam/uptime-kuma:2@sha256:91e963bfda569ba115206e843febb446f473ab525add4e08b2b9e3beffa16985
          imagePullPolicy: Always
          volumeMounts:
          - name: data
            mountPath: /app/data
          ports:
            - containerPort: 3001
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc