apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: uptime-kuma
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
