apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-proxy-sonarr-cm
  namespace: shared-authentication
data:
  oauth2-proxy.cfg: |
    provider = "keycloak-oidc"
    oidc_issuer_url = "https://auth.hoareau-marion.eu/realms/milkyway"
    client_id = "sonarr_v2"
    http_address = "0.0.0.0:4180"
    email_domains = [ "*" ]
    allowed_roles = [ "sonarr_v2:sonarr-user" ]
    skip_auth_regex = [ "^/api/.*", "^/[0-9]+/api.*" ]
    whitelist_domains = [ ".hoareau-marion.eu" ]
    upstreams = [ "http://sonarr-webui.sonarr.svc.cluster.local:8989/" ]
    pass_host_header = true
    reverse_proxy = true
    skip_provider_button = true