apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-sonarr-route-to-auth
  namespace: shared-authentication
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: sonarr
  to:
    - group: ""
      kind: Service
      name: auth-sonarr