---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oauth2-proxy-creds-sonarr
  namespace: shared-authentication
spec:
  encryptedData:
    client-secret: AgDANb5ADyPFalTB+vv9JzwoOkniYe7JmtXUgT9etWJtIVI6E+P4AvrSV+NDEN2Cgdk25iVMwRGa/GlQg4CATffDSiy3TAG60c/tX0c0Ne1HE4Z6s/gfo4/G5Ea/zPsWR9Z8/mYMYLwIg0Uf0OHOAlVGLPO0nL151n6X+Rv3zvGlc2JrF4E5V6LOH91fKo0BOnmtieYoZGm1QXki02k4BQNohUydo6vu771PP3L2wNb27/M0i6NrVLaQhMMhO2HcRYsxFDToZKRSupZ3BWCcxI3mVfKmRkB1k4Z1Qa2g0spefp9cPi93hwOegs/9kdfzGnqa29wc//qqymqxgN50gIOj1MtcD0JepDEidpvYeYgy8MZ0lkW/DtnJ8YY0jZEKBi0LfJllj/h20tuaWWNcGIwj4gv7+xNVukWZWIF1HSfvgyMs9juYmG4OyzjElB+r1FVp++kn8i7bllMaY1DUjGcQTYxfRVLke9V5HVHOx3nCxwDHXcfdN1TbityHzk+4vLoD2Xzz66r1l+JJPs6RzRecLYDapBnjjB5HiFLx4XE70Ofe5g3LkIsPkh4oRPBbqnByR2qEHaKQ8YTBjPVQmJQasQO5fyDyjKoU89gJhjQO1ByzrLUAxaw4Kfd+H/63KsIjeZrkSbS/h/eVQzhAuhjewUxiArJLVY52w/0AZnIxqz4/PS5OMkgMhFDSRZfUA0FCPzVItbfJjsQSwMbcsc4XSacuGqk565YpIhXjTlrx+w==
    cookie-secret: AgDIU82HvrKp49VGI1PWmaePQ/pvndOhikJa++V58J6VolNSkdAluQ23eiMkvpEpbqRNGL1KC2WMhNOtzto4NyIiu206MrNtKgxno+ppgUeGNC9T4ck8i1dFdV3tms+vzAmoOiWHBzIOt4AoqVoIU3TZ6quOy+ooLpqJ6naENCkCZpkETgV+M6ijupoIcdzIL/b5rdDsVeudHC1oG6rI0qcRyT5O36JEVDy4/9rNXc8EqcIWsfhQlnDXxAHwRAG0vXKu3nol0YazSgJBgXKSRSLdt/w97NhpSIyD1vFnvDq8R9IwyGy8bwfFUDreHcfDFOOyqGTArnTbKsplPWusOgaD0wGo0BtiieJJzLyQF6wF2e38vjBq5Ycmb6sfWhOoMXGenxlTucDwTuYYdeNTq1sG86sftWkNtlA5nfb8uOytas6ko6M4HcEUNKjkNv6UDVb1gUKUTa3kWyaGEk6GQ9mWdg13zV533j0jK8HJuWj3OnQ6T3AZL8mkNDKqHwR2U9QI2JQKuBBX8MED4uapGO9Nd0MlAgTexeho8I8xjCjiqWp6+jJZyqHFSEi/X9Py4kR2f8oBbEU6vYOe2iRVdPcRjlCqoMF1HHZPGFSiETZEPDo6XcoAIEa430UDbpdOkZpe4Swvx/PWc99DEEdEybC9ZsaY6vakYo2K2ljk/ypieQFQiYkdFs4fa9/4Ly7tiOAUotbZkrgOO9RhfUq+wjbJ0ZltnzCPKaiJ+90KXiy7BYvcW/ZhWq0b4fTpaA==
  template:
    metadata:
      name: oauth2-proxy-creds-sonarr
      namespace: shared-authentication
    type: Opaque
