# apps/qbittorrent/qbittorrent-torrents-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-torrents-pv
spec:
  capacity:
    storage: 6000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: media-nas
  nfs:
    server: truenas.local.hoareau-marion.eu
    path: /mnt/homelab-pool/media_data/torrents
