---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gluetun-secrets
  namespace: qbittorrent
spec:
  encryptedData:
    WIREGUARD_PRIVATE_KEY: AgCI1mK1E73t6qkYtMqgL9bUEF6HqZyQsZ1C4/pNGOl5RCO91FJE9qysHOas5o85eXPYdGjbfE080Vw7Rg6l8jIUt5FLjtqoD3J90jqIs8xK8UnqJtBDdqxlBozEF9QR8OnedVIxL19DRIx82EFDRFXm/vXhUh9EEBj3SkPEcZ+ajR44XCmC+TYs1AQV3h3luQG8HuM8IE/g2IBSCYbFMRsotQ3An1da1+pNI4gEQUIxNVSVVSjwEY2iqgfdjPZ1VutlC42n5CrW1eGUca1KtxH+XfvqPBvb8s3CvG9jmOwF8BzC+sdKstXBEkJ0QshiBccQ2Mycg5MmyfhHniB1QD9d60dcGj26OYBQuPTrJWuu3EHKa2tCK5nXGQj910VV05QaHXbAzZth/0svF4vArF9rXbRAAsfLe/yf/+5tM8kiObU6+ytHfwPWg+atGzv5eL4hL9GjsvpmH3k89DO5GdzocIJwngeHJOwbCIpquOSDeHE81tGhaXGTCiPkD2czHQIGCLtgjXE5qjOoMDhzvQIFd7CwQMK5TuFyG+FB/LpPNYd1RPRIuNZKI0eMn/qNxRffIhNCAJXmJUhMxcSOZynLERULzg5jJxnar4yJlwzbjyElQ0wGGANxenmbx4co6i5+WRoR6TfcTH45g+1KPUIhikyRwH/OMSkSEY1BSZG78VVz5Dx5r9cnToy0Oh0oQE/Zl6iym+LLvfCL9oEmC4XS6jRUQ8srvteUezLwUAY+iKTsib2xIqRcZksnRw==
  template:
    metadata:
      name: gluetun-secrets
      namespace: qbittorrent
    type: Opaque
