apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        affected_vlan: "50"
      containers:
      - name: redis
        image: valkey/valkey:9@sha256:c123e3715db63d06d4ad6964884037aa0d5d4d703939b9929954112889708e1d
        ports:
        - containerPort: 6379