apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: grafana-loki
data:
  loki.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
    common:
      path_prefix: /loki
      storage:
        filesystem:
          chunks_directory: /loki/chunks
          rules_directory: /loki/rules
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory
    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
    ruler:
      alertmanager_url: http://localhost:9093

    compactor:
      working_directory: /loki/compactor
      shared_store: filesystem
      compaction_interval: 10m
      retention_enabled: true          
      retention_delete_delay: 2h      
      retention_delete_worker_count: 15

    limits_config:
      retention_period: 14d            
      enforced_metric_name: ""
      reject_old_samples: true
      reject_old_samples_max_age: 168h