apiVersion: apps/v1
kind: Deployment
metadata:
  name: opnsense-exporter
  namespace: prometheus-exporters
  labels:
    app: opnsense-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opnsense-exporter
  template:
    metadata:
      labels:
        app: opnsense-exporter
    spec:
      nodeSelector:
        affected_vlan: "50"
      containers:
        - name: opnsense-exporter
          image: ghcr.io/athennamind/opnsense-exporter:0.0.17@sha256:04a28ad984a091ea1e8371cf515da8b38b1d00416f53e6b5c9d68fec39d92ce0
          imagePullPolicy: IfNotPresent
          args:
            - "--opnsense.protocol=https"
            - "--opnsense.address=opnsense.home.hoareau-marion.eu"
            - "--exporter.instance-label=opnsense"
            - "--web.listen-address=:8080"
          ports:
            - containerPort: 8080
              name: fw-metrics
              protocol: TCP          
          envFrom:
            - secretRef:
                name: opnsense-secrets
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 64Mi