---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opnsense-secrets
  namespace: prometheus-exporters
spec:
  encryptedData:
    OPNSENSE_EXPORTER_OPS_API_KEY: AgAkscSssiyycefLCH6V22Dyv/HQLL+JlilRYug6J5aNbdN90MOPOXgORRcy1QlrBT7kOkKY4TxW53mpgP1gR3R91gGLI1NPBuOc/bnO3yvTcom3EOeK2u5lN4sVQnrtHFrS//4gO2Svqj1GFEfESl/hDRQCdYVWO9IAd8CR6yIhYQ/KIEzghACDwLJqw/7di28pnYWp9K33A3jcCY4KJ2iA/VQsuv8zxbjvVwpJaEKQKq5aCYDm4sKyLAPfTWq87BIInjScYBICarWvWp4Ez3P2lEupCACouPwasnTWwWCz1gBf6S6XXe9Du/bSsrDNApocvV6SGov3m1H+xuhJ2TLSPWfwOsuSVTpkT6eyOPpScR7rMqSDW5xYdJpoquMrBCp3U7NQNMSqZM6yQNF4ZGWO0XkNGYB4K8SPfGQ3UBNywOBJKr2PL+rkd6+H+Ha4Ve8imVem7jIlt48B9p4JQVgqJNa1eD9mPFZ/3FhHVD6L3ceOtZngz/he6TJ7gy9sK6CiyhoGZxJXwlzBOmxIggOpRUdWJqAaW++HuHf+3NVsbB8jm9FilDha1BNK+ECbYtlYpHisYdvrY/S1eMLFDh3NGV4w1X+oR2Xt1sWKC8/6geraGr2H2MoMI7wE/hsEbbxxxwubXjC7fIh8KtSfEmWqxuc2NjxCkNNGfRAgX7Hnb48RwHz3ZEOMooBYkpb83WQv2LIjFi7da9qt7ATOG3hlSKwWXrrSFYY2tLavQpV+CGWImn6lxPQiUsj9cogGfNI8YFVBZBAo4bGRXNFnKaxNui/pXD+dQw8mrMZ8QcObbA==
    OPNSENSE_EXPORTER_OPS_API_SECRET: AgBacSWhWxZ1FxVWtIlawqZB05yXvLUczJ1M/J51DATH3UMYaqSL3IezKi2RUt8cY99tH7wz0YGLml9BA6EEkATTyiSPDigCddR+4Xy4aA26fDOd2HsDqClKSyD+b/0KC0MozqasiuSsMDvj62jUfLCs7UtujYwR0yRKoNFhHMD5+muUhlqb824vViSEV5CsRtXh/KYxXYNvznGxDNNvNr+K4HDaGnaQNQ7g5iVdRc0H0lTtWILk90cVnYX1gE2gSQaiVkJpzZU5eHlTCKhaKSkiSkKQFxj74/O9a99GkePzIDHP1VY9mcUsAtNozt9G/ZM+vS3PQRPVmf5pxJKdwbxMpRmCTd2UOIVtMsRem9b2WhrPeNVNzCuZLbw4RjOSi9TE6SmUUAI5DvTtF778EIgj0tnk8+k+BgVmzSayBj1FntvSAmQ8WhkR35t+77JXNQTM82vQFsZPTNPbCClEOW1xfQd2nBBiN7OR6UmrAdg5H4lTV0qwOcTk6XlADEFuRvFLs133XdVLMYpfl73WJgqHj9CQiNbS45gC/TXF/O+tNUJb1gUG0TIv9nIuFb8y33I+83jTCB2s+zqFBhSkzlxlCNwbPieU5z8uQorxawFrjLxxZlw/kP5EU96Rgky2RzAfK50RYMHNNx+aRHIJ0CKnUVvBRcpNwGTJHhfOiEfVvSW7fiJHuSE6MyA0VuivN1ST7T4JjqtODl9ks/t5I3n5ozb4EXyf1IikZvb5Q+KRhAbrnQDI2Qfjy3Ge9Lv0FkQTQapzX4KNpcuKfd99o8iS58wTmQNKwhma/7XzHUAC0w==
  template:
    metadata:
      creationTimestamp: null
      name: opnsense-secrets
      namespace: prometheus-exporters
    type: Opaque
