apiVersion: v1
kind: Service
metadata:
  name: opnsense-exporter-svc
  namespace: prometheus-exporters
spec:
  selector:
    app: opnsense-exporter
  ports:
    - name: fw-metrics
      port: 8080
      targetPort: 8080