apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      nodeSelector:
        affected_vlan: "50"
      initContainers:
      - name: setup-run
        image: busybox
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        command:
          - sh
          - -c
          - |
            chmod 0755 /run
            chown 3103:3100 /run
            chown -R 3103:3100 /config
        volumeMounts:
        - name: run-tmpfs
          mountPath: /run
        - name: config
          mountPath: /config
      containers:
      - name: radarr
        image: lscr.io/linuxserver/radarr:6.1.1.10360-ls300
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 3103
          runAsGroup: 3100
        envFrom:
        - configMapRef:
            name: config-map
        ports:
        - name: radarr
          containerPort: 7878
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /config
        - name: media-data
          mountPath: /media_data
        - name: run-tmpfs
          mountPath: /run
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "1"
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: config-pvc
      - name: media-data
        persistentVolumeClaim:
          claimName: media-data-pvc
      - name: run-tmpfs
        emptyDir:
          medium: Memory
