apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sftpgo-data-pvc
  namespace: sftpgo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs-client