apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sftpgo-home-pvc
  namespace: sftpgo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client