apiVersion: v1
kind: ConfigMap
metadata:
  name: cm
  namespace: lubelogger
data:
  EnableAuth: "true"
  LANG: "en_US.UTF-8"
  LC_NUMERIC: "fr_FR.UTF-8"
  LC_MONETARY: "fr_FR.UTF-8"
  LC_TIME: "fr_FR.UTF-8"
  OpenIDConfig__Name: "Keycloak"
  OpenIDConfig__ClientId: "lubelogger"
  OpenIDConfig__AuthURL: "https://auth.hoareau-marion.eu/realms/milkyway/protocol/openid-connect/auth"
  OpenIDConfig__TokenURL: "https://auth.hoareau-marion.eu/realms/milkyway/protocol/openid-connect/token"
  OpenIDConfig__RedirectURL: "https://lubelogger.hoareau-marion.eu/Login/RemoteAuth"
  OpenIDConfig__Scope: "openid email profile"
  OpenIDConfig__UsePKCE: "true"
  OpenIDConfig__ValidateState: "true"Speckled-Enslave4-Voucher-Calzone