---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret
  namespace: lubelogger
spec:
  encryptedData:
    client-secret: AgB/o3lawPJ1WWe8CvNiHZjLM/TERbIc6dJ2yNc7SfT50YDOdXuNbcKWwpHV+jjlq/PuOtz1ccrS9taalPlEAyuuMT58AnQ8VNHh5zJn18cb7277CjkmfIS9dZVtadEhgrLp59sXN5tpTJXROrUyoRxuXiCVfi6adHecE47GhzBDqhkzlR8CQlRzvPvjfxyzNPppJ6z6O8QVv+Wiq+GMecXwOA+OEZ8UPsG2c/9NYRiPVVetPuFKnqd2UG+52l1ihYxkyFKA/IisuVhdmkeVxuPJBi0C9wNJJvzGp4JL8ym3qw67a8U17M8BVxdd/9YgGzn3FvPIH1rL3PgsGDXBLrD873Qk+w3R7HmeXGItKLrTwZboON41R2ydVt7PxHf+c8h3zwhcVHXQrb89oVUKbJSKj+fulFA/V/gebAAUFPUO2AX+58e3sa4GT+swo2ljSQ7u1hcch0kofNkWSH3zMYm1Hcabp6Tpj07/q2L8zvDnvA7vX+KC4VVFGLYvfS1GvsFCA0V7WEekeQLeapXY7Wqh7iuPDAfnVfs1umTaSMZ71cfLrN2Ck7mtewF98+zRq2i/f2CXIv8mGtxku5K2W/hop7twVtsG50/N47nNJv1oe4O7diUNDZ7LtxLfdEoycU/sspsNE9NyBMNDO5eXTbDRdy+Iq81e43H1DDMDz5kfD2HQDq/6Rmi7f/1kaboI7LRbl5DHqVzeNbZVjOz3ubn+/hYuH9Zh5eVBYpCa25o/xnEY06RvI5hxiYdGkkaKPFYqY7fPkI3fYD+LMhgvJfnLif8mYfSI71DUPbrYQ+F7igeAGr1+8g==
  template:
    metadata:
      creationTimestamp: null
      name: secret
      namespace: lubelogger
    type: Opaque
