apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: sparkyfitness-route
  namespace: sparky-fitness
spec:
  parentRefs:
  - name: ingress-gateway
    namespace: cluster-gateway
    sectionName: sparky-https
  hostnames:
  - "sparky-fitness.hoareau-marion.eu"
  rules:
  # Frontend static files and SPA routes
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: sparkyfitness-frontend
      port: 3004  # Nginx container port
  # Backend API calls  
  - matches:
    - path:
        type: PathPrefix
        value: /api
    backendRefs:
    - name: sparkyfitness-server
      port: 3010
