apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-proxy-moonlight-cm
  namespace: shared-authentication
data:
  oauth2-proxy.cfg: |
    provider = "keycloak-oidc"
    oidc_issuer_url = "https://auth.hoareau-marion.eu/realms/milkyway"
    client_id = "moonlight"
    http_address = "0.0.0.0:4180"
    email_domains = [ "*" ]
    allowed_roles = [ "moonlight:moonlight-user" ]
    set_xauthrequest = true
    pass_user_headers = true
    set_authorization_header = true
    set_xheader_user = true
    whitelist_domains = [ ".hoareau-marion.eu" ]
    upstreams = [ "http://moonlight.moonlight.svc.cluster.local:8080" ]
    pass_host_header = true
    reverse_proxy = true
    skip_provider_button = true