---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oauth2-proxy-creds-moonlight
  namespace: shared-authentication
spec:
  encryptedData:
    client-secret: AgCZfMadJkzX/s3WjqN7uLyLmfaue4mBEhHQznleTTJWTmJ/vsbYPh2on+wmHwhe/LTv2ErMwgnH7Eg3vl/R50TKzDCqMXEFjN+B80TVhJj2KnSq4OwUB4124wujqoTiDsKhhTsCjkSoCloo0bTGUMy/tfMeApKphiyY26TCEwpsNh7oDQ1s7P68wAgjoBjWxK4cX0wD4H27x0aqbsUqnGKkP9lyWT6/9OuNfJiPTb10I5kRNSNX59eRV6zSbWZ1mhUh5ZMFGjF7mMYK9240UCDQtU54OwiXY1/gEf6XIJXrI5oFvasaHD8cxS9GVzJ+MOw7QAZ3Tjz7E65s9qN+T72B7JWuRk/lKfl0RG6OVBbzcYkz0wjoIbsw9ZIu6iqgmX0RY2wJ7NStT+iZYbPMUvM8cqC7uyubriEZm7m+1N3Xon688v48XoypzEg0L+bCTbgA3s1pCaSOSlwOVSOyiuDrfis2iW5mau82SB0zv5Vtw0eYPx+8v86losmvRObzLYepNhrh14rAWpd85xLl8Wp9gGoAliV9jUTCbsi6aKKzwK2UlsBqjghZGevk1buDWqsnW82xXJDVaOaLMJe394Jn2/KLjiZ2WRhC6GwkuLiANID7ZOrG0q7aFyYvYplT/uE7QJTiFHwoU3O3BXHI5gMvTt0A+DiFALbaxcYnJWtRWdXNHe4zrNko8yPW2Fjq69cO0OWK49Je41Cf+LQX89ymiOybVJeGUQto3SV3uqmuCg==
    cookie-secret: AgDROe3Ln4TT1Tei6q8jcisw0b2XGy4SOSbHO+o77ck3fRrgk2hKMUXw94Ur1NiIJrSO9VlhrgSTzWeJQGE10iZIgGtD0gtt83YS3d1+T9rCtGywYE/p34pAk/bhcVFFPJQXxydvU/aXsqQblEmi4Ir95EmMMq1YOTquvj1tKhtqvSkeqIjsQIco/Hp2AYkBmoYMELSow42wxCaSz0wvFcPOZaKyqzYFut5087SYu94YH/RQvl/KfkBL/pgqil+qqvQBYUULsfaKHWM+JQiRKTSiWwYNDvsWd2CJqBEI+16aWbO9sAfYGiFq1UVIwJgfyQXLje1X/SxEuXil3aErlz9lveC4hW+uymml4laqc/rlD+yqOk171sOlZT2T2yanYkpwbJXPG+/5xIRI5QAekWOgo89REI2nadQKJNxHWKEJmKm2SjRyexDVmRrEj59GmFezx/cYXWD2kUAog4RonRsEahSNR4bSGWqHSZzguLP0ux4NbuWECibJdOWJmGwH9GKuqOhW7xs/N2DmKLb3jCD5VetN3rC4A9nrxBKRiVqY+wnSpIQm5ApwjzDyn/Z3ZH9E5d2/I8BJBEIliQX5hO+VjkJtfOACcH5a/pKWISmRP0Ap/b89vyN1C8q65+xcar2KqWPQfOx+e2lIhrz6oQe6S4Krb//Pg8EhxCY9TT2ElVI5jN5mgn0me4Tn/zz2ASy2ed9gla28gzDVF0PLT/8Ks5YKy3v1yUmQEcurMj0+/Q==
  template:
    metadata:
      name: oauth2-proxy-creds-moonlight
      namespace: shared-authentication
    type: Opaque
