---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oauth2-proxy-creds-moonlight
  namespace: shared-authentication
spec:
  encryptedData:
    client-secret: AgCgTWkBkLRAkXgS2ARJO7VF0yJ12d0FmswK78n+l7xG6ylkmCDncbEEHJdPwQaR3FiOZXo8YNAQL/b94itq6ghDg8CUukvyLGy0SKzuZqYOe3QlquaMN0Rba7w1AuwPg+i6uQMaWj7TQrV583+W+B5Zi+cM8NJfdIYuXqZlLvIFQ8a33C8JEWDF+hH+uQBZeqfDelwXBvMEQ/1ug1JUkwKbyegZlp+Vyhp0ANWszW2sqRODfO3LtRYLVRqHOVCrxJuR3l6xcAKZye7WeMkCEPc1bXW60Pc+PsDAfC0Nyf4jr9iuSmbemCG0ZhOgxyFf7HBDMKmSYu9eBZj9B+0NZVfPMsutA+RwHp1v3nqWbc4glyhv9Swq1/O1s6Amn4z7eopddAUbactZ223PPUUi5SlkMpkXw/rWn5JdIwl2WuScoPhzCKvU/2RchGBKfUahValuRnNiSurB4lnM/0qg+FmNRCxpCxHXqzczZf5ROgHC7MpyVqvkajNNP1/k+UAYNT87JCqBDfUi4H9d8on+isRnTPdReJvFvjCfK0nu1h7ig3BUD16STuiZ8qpnnUKcenNQA/e/TCkGo1HMhz+6LBu9Xq6Oz6Xtu72MSXZr3KRe1ILpe9G1FW1n9Qb1lAssf2bMnfIZeewwPin5o9PckPzjJ2FcEbU4JhBtS5IvPVHPYjjS8VS7SnU1xNRoy4tYYV686pM3m2zi21BNMcOJ+jeTudKpEGw+UJ4hAIXRFRjoXg==
    cookie-secret: AgCtVkfH/JQ5doP3iZC9nmflJqociFvK7i4wjEQfFsbTGOkhsquF6wiD/9RZ0kcY3XbYvpHIYhYy/fj5nCWYIGzz5N80axbt4jSgY1YPvKDrZwzMisUVfKlh2cICEPq+L73M1OkwFnvpSyH1TS357XoIqdD+Sj6CDAyQDir3Z3SbUsdjnQ+cjWJlZPfJzyZ5zzBQqpcExosO2nD8RmNXTuAyN4qN+5NgXqc+cEpZP498hinPle+GCTCf7PHrCqfzRM6b1UIk9K9WwzyE/mRVQ0vkU/ziZKL4aSfD8kauh4KlYtMcaJcntAlvIfc8bjQunDPwx+BhpSorIsHX5JuKRhBlr0IKOaqAKxKcpVN6U1546Vfk4GN4mCd1gjedM7fj/x7vuFtjILZV/Yc3Qit3iL+Tm/uMHEFT5bsjAgx7l+Asz3cXP18eY6tYj5tL+YKBZcgu/nrXR0sm3kROXaV7mNiobizu1z2j3pq9Cn5E/gVfCkd6YXvxndLwztpZrOORFFdJnj71JoMJww8GpQ6UlWFnsPvM4oKxJURIhpn5G4W2ETOm509aJVpNmLg6N8KTHIaSW9ZjkxZtTz+qfNlM/UshgraKbHtU8PoyFhzwhj6D1/Uhq+n/3d5bh6vh0yHr/JrnEVetu96ObG4JCbbHZUMURGDHewmHOt4eq3XDfJ0O4MPuHEt5gRpB8F6eRd1o1D24WE8vmpRowd482g9bsEBYtk4C4uXU9jA8KQqXqrfDwB8I8qxVgjXto48uEg==
  template:
    metadata:
      name: oauth2-proxy-creds-moonlight
      namespace: shared-authentication
    type: Opaque
