apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: keycloak
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client
