apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-consume-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""               
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: openmediavault.local.hoareau-marion.eu      
    path: /export/paperless-consume  
