# apps/planka.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: planka
  namespace: argocd
  labels:
    hoareau-marion.eu/category: collaboration
spec:
  project: homelab
  source:
    repoURL: https://github.com/jhoareaumarion/homelab-kubernetes-apps
    targetRevision: HEAD
    path: apps/planka
    directory:  
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: planka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m