apiVersion: apps/v1
kind: Deployment
metadata:
  name: protonmail-bridge
  namespace: paperless-ngx
  labels:
    app: protonmail-bridge
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: protonmail-bridge
  template:
    metadata:
      labels:
        app: protonmail-bridge
    spec:
      containers:
        - name: bridge
          image: shenxn/protonmail-bridge:3.19.0-1@sha256:3717b4441130675dc9131196de9f9c5287d2ea21b138d83b0486429e1737638a
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 25
              name: smtp
            - containerPort: 143
              name: imap
          volumeMounts:
            - mountPath: "/root/"
              name: protonmail-data
      volumes: 
        - name: protonmail-data
          hostPath:
            path: /var/lib/protonmail-data
            type: DirectoryOrCreate