apiVersion: v1
kind: Service
metadata:
  name: proton-bridge.paperless-ngx.svc.hoareau-marion.eu
  namespace: paperless-ngx
spec:
  type: ExternalName
  externalName: protonmail-bridge-service.paperless-ngx.svc.cluster.local