apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: protonmail-bridge-pvc
  namespace: paperless-ngx
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client