apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      nodeSelector:
        affected_vlan: "50"
      initContainers:
      - name: setup-run
        image: busybox@sha256:fd8d9aa63ba2f0982b5304e1ee8d3b90a210bc1ffb5314d980eb6962f1a9715d
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        command:
          - sh
          - -c
          - |
            chmod 0755 /run
            chown 3101:3100 /run
        volumeMounts:
        - name: run-tmpfs
          mountPath: /run
      containers:
      - name: prowlarr
        image: lscr.io/linuxserver/prowlarr:2.4.0@sha256:536036aeb2c740d1a660ccf143b58a8bd6222f09010258fdfc10a538af7bec78
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 3101
          runAsGroup: 3100
        envFrom:
        - configMapRef:
            name: config-map
        ports:
        - name: prowlarr
          containerPort: 9696
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /config
        - name: run-tmpfs
          mountPath: /run
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1500m"
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: config-pvc
      - name: run-tmpfs
        emptyDir:
          medium: Memory