apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
  namespace: matrix
data:
  SYNAPSE_CONFIG_PATH: "/etc/synapse/homeserver.yaml"
  SYNAPSE_REPORT_STATS: "yes"
  SYNAPSE_SERVER_NAME: "matrix.hoareau-marion.eu"
  SYNAPSE_LOG_CONFIG: "/etc/synapse/log.config"