apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      nodeSelector:
        affected_vlan: "50" 
      containers:
        - name: grafana
          image: grafana/grafana:13.0.4
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana
            - name: grafana-datasources-vol
              mountPath: /etc/grafana/provisioning/datasources
              readOnly: true
          envFrom:
            - configMapRef:
                name: config-map
          env:
            - name: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
      volumes:
        - name: grafana-data
          persistentVolumeClaim:
            claimName: pvc
        - name: grafana-datasources-vol
          configMap:
            name: datasources