---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secrets
  namespace: grafana
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgBq9V112Dl9ulw/hacvdVwsrN6zHxL9FnXpupn5WjxXQkGQnwskFVJXLKCS+e/zfhj8Z7Q1Udnsjf+28vyJiq942Fi347vDqAjie/5+//PusCnOkeO80TsmGPhgmiC5BB1i53/UObv+gVBcFLU1GiS42tI/03UnzUHW9g2zU81sNv8EvYwqw0tz8el7BAo8RTJN1EeQ9qRXq8yOQjWlFdGN7xj7G4GUBtvd+oREzts69/aIP25Hs6evS1S08DEyADru0K+Daouc7qBfV/UPt5yF09ryveWaZPyUXBVgGdYHzRaQvL6+XD/zj2v+bl1Jnx8XtJ0hvM1ffsfgcQ9QeXm1zl7vPMCQnht52Y59guP0SCBuHyhG03pzcIXp4VDrm06f2xOVTV/CAKtQtKT9TxE83xDkZQZ30rJcavDfUdZcvF4n6X+lJ0QFi0N8vySlJn+yEubH0fj43aJymK8aVKmR3/wUGups+luvGym7SManIUsEU7S2N9dm7QO9V2VnXjaCuFrSL6RdAE3A/Q8pwpuRY+Sb0odKz8xV1WMmHk4tUi5yioQELQ72i3Oyao/xF7npQN/AcQlI5vFs6bJNMYW+d+1WbxBMVRFncJQOajUXaPbR0tx2djRfuhlfmWdb4LzE13/5lD2htCRHJ8E7rCJ38CH7Y4alrWNvgw7QQuuqi08cHrJFmxP2V3MR3d6URcMYAW7JrMJB5Jx9nMayZenQ9w+kcZZo+hGI565WW0WwnoZua/7G9jEQce9KUkxUPEO8NS+mz9ajYEnHkMZEhWfPi5d0wcMh8tSk0jSAskgT6TBUYe9lPA==
  template:
    metadata:
      creationTimestamp: null
      name: secrets
      namespace: grafana
    type: Opaque
