apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: grafana-alloy
data:
  config.alloy: |
    discovery.kubernetes "pod" {
      role = "pod"
    }

    discovery.relabel "pod_logs" {
      targets = discovery.kubernetes.pod.targets

      rule {
        source_labels = ["__meta_kubernetes_namespace"]
        action = "replace"
        target_label = "namespace"
      }
      rule {
        source_labels = ["__meta_kubernetes_pod_name"]
        action = "replace"
        target_label = "pod"
      }
      rule {
        source_labels = ["__meta_kubernetes_pod_container_name"]
        action = "replace"
        target_label = "container"
      }
    }

    loki.source.kubernetes "pod_logs" {
      targets = discovery.relabel.pod_logs.output
      forward_to = [loki.write.endpoint.receiver]
    }

    loki.write "endpoint" {
      endpoint {
        url = "http://loki.grafana-loki.svc.cluster.local:3100/loki/api/v1/push"
      }
    }