apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ryot-database-pvc
  namespace: ryot
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
