apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
  namespace: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      # Scrape Node Exporter
      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names: ['prometheus-exporters']
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: node-exporter-svc

      # Scrape PVE Exporter
      - job_name: 'pve-exporter'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names: ['prometheus-exporters']
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: pve-exporter-svc