# apps/prometheus/exporters/prometheus-exporter.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-exporter
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://github.com/jhoareaumarion/homelab-kubernetes-apps
    targetRevision: HEAD
    path: apps/prometheus/exporters
    directory:  
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus-exporter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 0
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
