apiVersion: apps/v1
kind: Deployment
metadata:
  name: truenas-graphite-exporter
  namespace: prometheus-exporters
  labels:
    app: truenas-graphite-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: truenas-graphite-exporter
  template:
    metadata:
      labels:
        app: truenas-graphite-exporter
    spec:
      nodeSelector:
        affected_vlan: "50"
      containers:
        - name: graphite-exporter
          image: prom/graphite-exporter:v0.16.0
          imagePullPolicy: IfNotPresent
          args:
            - "--graphite.mapping-config=/etc/graphite-exporter/graphite_mapping.conf"
          ports:
            - containerPort: 9109
              name: graphite-in
              protocol: TCP
            - containerPort: 9108
              name: metrics
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/graphite-exporter
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 64Mi
      volumes:
        - name: config
          configMap:
            name: truenas-graphite-exporter-config