apiVersion: v1
kind: Service
metadata:
  name: truenas-graphite-exporter-svc
  namespace: prometheus-exporters
  labels:
    io.cilium/lb-pool: vlan50-pool-tcp-ingress
spec:
  type: LoadBalancer
  ports:
    - name: graphite-in
      port: 2003
      targetPort: 2003
      protocol: TCP
    - name: metrics
      port: 9108
      targetPort: 9108
      protocol: TCP
  selector:
    app.kubernetes.io/name: truenas-graphite-exporter