apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: animes-pvc
  namespace: sonarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  storageClassName: media-nas
  volumeName: sonarr-animes-pv
